import {randomUUID} from "node:crypto";
import type {EjercicioRepository} from "@/modules/ejercicios/domain/repository";
import type {PlantillaEjercicioRepository,PlantillaSesionRepository} from "../domain/repository";
import {plantillaEjercicioSchema,plantillaSesionSchema} from "../domain/schema";
import {PlantillaAdminError} from "./errors";
import {plantillaFieldsSchema,plantillaExerciseInputSchema,type PlantillaExerciseInput,type PlantillaFields} from "./schemas";

export function createPlantillaAdminService(deps:{sessions:PlantillaSesionRepository;exercises:PlantillaEjercicioRepository;catalog:EjercicioRepository}){const{sessions,exercises,catalog}=deps;
 function normalize(sessionId:string,inputs:PlantillaExerciseInput[]){const parsed=inputs.map(input=>plantillaExerciseInputSchema.parse(input));const blockOrders=[...new Set(parsed.map(item=>item.Orden_Bloque))].sort((a,b)=>a-b);return blockOrders.flatMap((oldBlock,index)=>parsed.filter(item=>item.Orden_Bloque===oldBlock).sort((a,b)=>a.Orden_Ejercicio-b.Orden_Ejercicio).map((item,itemIndex)=>plantillaEjercicioSchema.parse({...item,Plantilla_Ejercicio_ID:item.Plantilla_Ejercicio_ID??randomUUID(),Plantilla_Sesion_ID:sessionId,Orden_Bloque:index+1,Orden_Ejercicio:itemIndex+1})));}
 async function validateCatalog(normalized:ReturnType<typeof normalize>,currentReferences:Map<string,string>){const all=await catalog.findAll({includeArchived:true});const byId=new Map(all.map(item=>[item.Catalogo_ID,item]));for(const item of normalized){const master=byId.get(item.Catalogo_ID);if(!master)throw new PlantillaAdminError("CATALOGO_NOT_FOUND",400);if(!master.Activo&&currentReferences.get(item.Plantilla_Ejercicio_ID)!==item.Catalogo_ID)throw new PlantillaAdminError("ARCHIVED_EXERCISE_NOT_AVAILABLE",400);}}
 return {
  async list(filters:{search?:string;objective?:string;muscle?:string}={}){const[all,composition]=await Promise.all([sessions.findAll(),exercises.findAll()]);const search=(filters.search??"").trim().toLocaleLowerCase("es");return all.filter(item=>(!search||item.Nombre_Plantilla.toLocaleLowerCase("es").includes(search))&&(!filters.objective||item.Objetivo===filters.objective)&&(!filters.muscle||item.Grupo_Muscular_1===filters.muscle||item.Grupo_Muscular_2===filters.muscle)).map(session=>({session,exerciseCount:composition.filter(item=>item.Plantilla_Sesion_ID===session.Plantilla_Sesion_ID).length})).sort((a,b)=>a.session.Nombre_Plantilla.localeCompare(b.session.Nombre_Plantilla,"es"));},
  async filters(){const all=await sessions.findAll();return{objectives:[...new Set(all.map(x=>x.Objetivo))].sort(),muscles:[...new Set(all.flatMap(x=>[x.Grupo_Muscular_1,x.Grupo_Muscular_2]).filter(Boolean))].sort()};},
  async create(input:PlantillaFields){const fields=plantillaFieldsSchema.parse(input);const session=plantillaSesionSchema.parse({...fields,Plantilla_Sesion_ID:randomUUID(),Fecha_Carga:new Date().toISOString().slice(0,10)});await sessions.create(session);return session;},
  async get(id:string){const session=await sessions.findById(id);if(!session)throw new PlantillaAdminError("PLANTILLA_NOT_FOUND");const items=await exercises.findBySesion(id);const allCatalog=await catalog.findAll({includeArchived:true});const byId=new Map(allCatalog.map(item=>[item.Catalogo_ID,item]));return{session,exercises:items.map(item=>({item,catalog:byId.get(item.Catalogo_ID)??null})),catalog:allCatalog.filter(item=>item.Activo)};},
  async save(id:string,fieldsInput:PlantillaFields,exerciseInputs:PlantillaExerciseInput[]){const previous=await sessions.findById(id);if(!previous)throw new PlantillaAdminError("PLANTILLA_NOT_FOUND");const current=await exercises.findBySesion(id);const fields=plantillaFieldsSchema.parse(fieldsInput);const normalized=normalize(id,exerciseInputs);await validateCatalog(normalized,new Map(current.map(item=>[item.Plantilla_Ejercicio_ID,item.Catalogo_ID])));const updated=plantillaSesionSchema.parse({...previous,...fields,Plantilla_Sesion_ID:id});await sessions.update(updated);try{await exercises.replaceForSesion(id,normalized);}catch(error){await sessions.update(previous).catch(()=>undefined);throw error;}return{session:updated,exercises:normalized};},
 };
}
