import type { EjercicioRepository } from "@/modules/ejercicios/domain/repository";
import type { RutinaEjercicioRepository, RutinaSesionRepository } from "@/modules/rutinas/domain/repository";
import type { RegistroProgresoRepository } from "@/modules/progresos/domain/repository";
import { EntrenamientoAlumnoError } from "./errors";
function todayInArgentina(now: Date) { return new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Buenos_Aires", year: "numeric", month: "2-digit", day: "2-digit" }).format(now); }
export function createEntrenamientoAlumnoService({ sessions, items, catalog, progress, now = () => new Date() }: { sessions: RutinaSesionRepository; items: RutinaEjercicioRepository; catalog: EjercicioRepository; progress?: RegistroProgresoRepository; now?: () => Date }) {
  async function ownedSession(alumnoId: string, rutinaId: string) { const session = await sessions.findById(rutinaId); if (!session) throw new EntrenamientoAlumnoError("RUTINA_NOT_FOUND"); if (session.Alumno_ID !== alumnoId) throw new EntrenamientoAlumnoError("RUTINA_FORBIDDEN", 403); return session; }
  return {
    async list(alumnoId: string) { const today = todayInArgentina(now()); const own = await sessions.findByAlumno(alumnoId); const pending = own.filter((session) => !session.Entrenamiento_Completado); const next = pending.find((session) => session.Fecha >= today) ?? pending.at(-1) ?? null; const withState = own.map((session) => ({ session, state: session.Entrenamiento_Completado ? "completado" as const : session.Rutina_Sesion_ID === next?.Rutina_Sesion_ID ? "próximo" as const : session.Fecha < today ? "pendiente" as const : "próximo" as const })); return { next, upcoming: withState.filter(({ session }) => session.Fecha >= today), previous: withState.filter(({ session }) => session.Fecha < today).reverse() }; },
    async detail(alumnoId: string, rutinaId: string) { const session = await ownedSession(alumnoId, rutinaId); const [composition, allCatalog, allProgress] = await Promise.all([items.findBySesion(rutinaId), catalog.findAll({ includeArchived: true }), progress?.findAll() ?? Promise.resolve([])]); const catalogById = new Map(allCatalog.map((exercise) => [exercise.Catalogo_ID, exercise])); const ownProgress = allProgress.filter((row) => row.Alumno_ID === alumnoId).sort((a, b) => b.Fecha_Registro.localeCompare(a.Fecha_Registro)); const blocks = [...new Set(composition.map((exercise) => exercise.Orden_Bloque))].sort((a, b) => a - b).map((order) => { const exercises = composition.filter((exercise) => exercise.Orden_Bloque === order).sort((a, b) => a.Orden_Ejercicio - b.Orden_Ejercicio).map((item) => ({ item, catalog: catalogById.get(item.Catalogo_ID) ?? null, latest: ownProgress.find((row) => row.Catalogo_ID === item.Catalogo_ID) ?? null })); return { order, name: exercises[0]?.item.Tipo_Bloque ?? `Bloque ${order}`, exercises }; }); return { session, blocks }; },
    async setCompleted(alumnoId: string, rutinaId: string, completed: boolean) { const session = await ownedSession(alumnoId, rutinaId); const updated = { ...session, Entrenamiento_Completado: completed, Fecha_Completado: completed ? todayInArgentina(now()) : null }; await sessions.update(updated); return updated; },
  };
}
