import Link from "next/link";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { ExerciseBadge } from "@/components/admin/exercise-badge";
import { requireAdmin } from "@/modules/auth/infrastructure/current-user";
import { getEjercicioAdminService } from "@/modules/ejercicios/infrastructure/ejercicio-admin-service-factory";

export default async function EjerciciosPage({searchParams}:{searchParams:Promise<{q?:string;tipo?:string;estado?:string}>}) {
 await requireAdmin();const params=await searchParams;const status=params.estado==="archived"?"archived":params.estado==="all"?"all":"active";const service=getEjercicioAdminService();const[items,types]=await Promise.all([service.list({search:params.q,type:params.tipo,status}),service.types()]);
 return <main className="app-page space-y-6"><PageHeader eyebrow="Administración" title="Catálogo de ejercicios" description={`${items.length} ejercicios encontrados`} actions={<Link className="inline-flex min-h-11 items-center rounded-xl bg-violet-700 px-5 font-bold text-white" href="/admin/ejercicios/nuevo">Nuevo ejercicio</Link>}/><form className="surface grid gap-3 rounded-2xl p-4 sm:grid-cols-3"><label className="space-y-1 text-sm font-semibold">Buscar<input className="min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal" defaultValue={params.q??""} name="q" placeholder="Nombre del ejercicio"/></label><label className="space-y-1 text-sm font-semibold">Tipo<select className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 font-normal" defaultValue={params.tipo??""} name="tipo"><option value="">Todos</option>{types.map(type=><option key={type} value={type}>{type}</option>)}</select></label><label className="space-y-1 text-sm font-semibold">Estado<select className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 font-normal" defaultValue={status} name="estado"><option value="active">Activos</option><option value="archived">Archivados</option><option value="all">Todos</option></select></label><button className="min-h-11 rounded-xl border border-violet-700 px-4 font-semibold text-violet-700 sm:col-span-3">Aplicar filtros</button></form>
 <div className="grid gap-4 md:grid-cols-2">{items.map(item=><Card className="flex h-full flex-col justify-between gap-5" key={item.Catalogo_ID}><div><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{item.Ejercicio}</h2><p className="text-sm text-slate-600">{item.Tipo_de_Ejercicio}</p></div><ExerciseBadge active={item.Activo}/></div><p className="mt-3 text-sm text-slate-500">{item.Video||item.Video_Adicional?"Video disponible":"Sin video"}</p></div><div className="flex flex-wrap items-center gap-2"><Link className="inline-flex min-h-11 items-center rounded-xl border border-violet-700 px-4 text-sm font-bold text-violet-700" href={`/admin/ejercicios/${encodeURIComponent(item.Catalogo_ID)}`}>Editar</Link>{item.Video?<a className="brand-link inline-flex min-h-11 items-center px-2 text-sm font-bold" href={item.Video} rel="noopener noreferrer" target="_blank">Ver video ↗</a>:null}</div></Card>)}</div>{!items.length?<EmptyState icon="⌕" title="Sin coincidencias" description="Probá con otro nombre, tipo o estado."/>:null}
 </main>;
}
