import Link from "next/link";
import { Card } from "@/components/ui/card";
import { ExerciseBadge } from "@/components/admin/exercise-badge";
import { requireAdmin } from "@/modules/auth/infrastructure/current-user";
import { getEjercicioAdminService } from "@/modules/ejercicios/infrastructure/ejercicio-admin-service-factory";

export default async function EjerciciosPage({searchParams}:{searchParams:Promise<{q?:string;tipo?:string;estado?:string}>}){await requireAdmin();const params=await searchParams;const status=params.estado==="archived"?"archived":params.estado==="all"?"all":"active";const service=getEjercicioAdminService();const[items,types]=await Promise.all([service.list({search:params.q,type:params.tipo,status}),service.types()]);
 return <main className="mx-auto max-w-6xl space-y-6 px-5 py-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-violet-700">Administración</p><h1 className="text-3xl font-black">Catálogo de ejercicios</h1><p className="text-slate-600">{items.length} ejercicios encontrados</p></div><Link className="inline-flex min-h-11 items-center justify-center rounded-lg bg-violet-700 px-4 py-2 font-semibold text-white" href="/admin/ejercicios/nuevo">Nuevo ejercicio</Link></div>
 <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-3"><label className="space-y-1 text-sm font-semibold">Buscar<input className="min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal" defaultValue={params.q??""} name="q" placeholder="Nombre del ejercicio"/></label><label className="space-y-1 text-sm font-semibold">Tipo<select className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 font-normal" defaultValue={params.tipo??""} name="tipo"><option value="">Todos</option>{types.map(type=><option key={type} value={type}>{type}</option>)}</select></label><label className="space-y-1 text-sm font-semibold">Estado<select className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 font-normal" defaultValue={status} name="estado"><option value="active">Activos</option><option value="archived">Archivados</option><option value="all">Todos</option></select></label><button className="min-h-11 rounded-lg border border-violet-700 px-4 font-semibold text-violet-700 sm:col-span-3">Aplicar filtros</button></form>
 <div className="grid gap-4 md:grid-cols-2">{items.map(item=><Link href={`/admin/ejercicios/${encodeURIComponent(item.Catalogo_ID)}`} key={item.Catalogo_ID}><Card className="h-full space-y-3 transition hover:border-violet-300"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{item.Ejercicio}</h2><p className="text-sm text-slate-600">{item.Tipo_de_Ejercicio}</p></div><ExerciseBadge active={item.Activo}/></div><p className="text-sm text-slate-500">{item.Video||item.Video_Adicional?"Video disponible":"Sin video"}</p></Card></Link>)}</div>{!items.length?<Card><p className="text-slate-600">No se encontraron ejercicios para estos filtros.</p></Card>:null}
 </main>;
}
