"use client";
import { useState, type FormEvent } from "react";
import type { Alumno } from "@/modules/alumnos/domain/alumno";
import type { Ejercicio } from "@/modules/ejercicios/domain/ejercicio";
import type { RutinaEjercicio, RutinaSesion } from "@/modules/rutinas/domain/rutina";
import type { AiProposal } from "@/modules/ai-planning/domain/schemas";
import { RutinaEditor } from "./rutina-editor";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
type Clarification={pregunta:string;opciones:string[]};type Result={status:"READY";propuesta:AiProposal|null;motivoInsuficiente:string|null}|{status:"NEEDS_CLARIFICATION";pregunta:string;opciones:string[]};const emptyId="00000000-0000-4000-8000-000000000000";
const messages:Record<string,string>={OPENAI_NOT_CONFIGURED:"El asistente IA no está configurado.",OPENAI_RATE_LIMIT:"El servicio alcanzó su límite temporal. Intentá más tarde.",OPENAI_UNAVAILABLE:"No pudimos contactar al asistente. Intentá nuevamente.",INVALID_CATALOG_REFERENCE:"La propuesta incluyó un ejercicio no disponible y fue rechazada.",EMPTY_CATALOG:"No hay ejercicios activos disponibles.",ALUMNO_NOT_FOUND:"El alumno ya no existe.",INVALID_MODEL_RESPONSE:"La respuesta no fue válida. Intentá nuevamente."};
export function AiRoutinePlanner({students,catalog}:{students:Alumno[];catalog:Ejercicio[]}){
 const[studentId,setStudentId]=useState(students[0]?.Alumno_ID??"");const[busy,setBusy]=useState(false),[error,setError]=useState(""),[proposal,setProposal]=useState<AiProposal|null>(null),[clarification,setClarification]=useState<Clarification|null>(null),[answer,setAnswer]=useState(""),[request,setRequest]=useState<Record<string,unknown>|null>(null),[useDraft,setUseDraft]=useState(false);const student=students.find(x=>x.Alumno_ID===studentId);
 async function call(body:Record<string,unknown>){setBusy(true);setError("");try{const response=await fetch("/api/admin/ia/rutinas",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const payload=await response.json()as Result&{error?:string};if(!response.ok)throw new Error(payload.error);if(payload.status==="NEEDS_CLARIFICATION"){setClarification({pregunta:payload.pregunta,opciones:payload.opciones});setRequest(body);return}setClarification(null);if(!payload.propuesta){setError(payload.motivoInsuficiente??"No hay información suficiente para una propuesta responsable.");return}setProposal(payload.propuesta)}catch(e){setError(messages[e instanceof Error?e.message:""]??"No se pudo generar la propuesta.")}finally{setBusy(false)}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const num=(name:string)=>{const value=String(f.get(name)??"");return value?Number(value):null};await call({Alumno_ID:studentId,Objetivo_Sesion:f.get("Objetivo_Sesion"),Objetivo_Otro:f.get("Objetivo_Otro"),Foco:f.get("Foco"),Duracion_Minutos:num("Duracion_Minutos"),Cantidad_Bloques:num("Cantidad_Bloques"),Indicaciones_Adicionales:f.get("Indicaciones_Adicionales"),Aclaracion:null})}
 async function clarify(){if(request&&clarification&&answer.trim())await call({...request,Aclaracion:{pregunta:clarification.pregunta,respuesta:answer.trim()}})}
 if(useDraft&&proposal&&student){const items=proposal.Bloques.flatMap(block=>block.Ejercicios.map(exercise=>{const item:RutinaEjercicio={Rutina_Ejercicio_ID:crypto.randomUUID(),Rutina_Sesion_ID:emptyId,Catalogo_ID:exercise.Catalogo_ID,Tipo_Bloque:block.Tipo_Bloque,Orden_Bloque:block.Orden_Bloque,Orden_Ejercicio:exercise.Orden_Ejercicio,Instrumento_Alternativo:"",Reps_Tiempo:exercise.Reps_Tiempo,Series:exercise.Series,Carga:exercise.Carga,Descanso:exercise.Descanso,RIR:exercise.RIR,Observaciones:exercise.Observaciones};return{item,catalog:catalog.find(x=>x.Catalogo_ID===exercise.Catalogo_ID)??null}}));const session:RutinaSesion={Rutina_Sesion_ID:emptyId,Alumno_ID:student.Alumno_ID,Dia_Entrenamiento_Semana:"Día 1",Fecha:new Date().toISOString().slice(0,10),Titulo:proposal.Titulo,Notas_Generales:proposal.Notas_Generales,Plantilla_Sesion_Origen_ID:null,Entrenamiento_Completado:false,Fecha_Completado:null};return <div className="space-y-5"><div className="rounded-xl border border-cyan-200 bg-cyan-50 p-4 text-sm text-cyan-950"><strong>✨ Propuesta generada con IA</strong> · Revisá y ajustá antes de guardar.</div><Button className="bg-slate-700" onClick={()=>setUseDraft(false)}>Volver a la propuesta</Button><RutinaEditor catalog={catalog} composition={items} createMode session={session} students={students}/></div>}
 return <div className="space-y-6"><form className="space-y-5" onSubmit={submit}><section className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-2"><label className="text-sm font-semibold">Alumno<select className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3" onChange={e=>{setStudentId(e.target.value);setProposal(null);setClarification(null)}} value={studentId}>{students.map(x=><option key={x.Alumno_ID} value={x.Alumno_ID}>{x.Apellido}, {x.Nombre}</option>)}</select></label><div className="rounded-xl bg-slate-50 p-3 text-sm sm:col-span-2"><p><strong>Objetivo general:</strong> {student?.Objetivo||"Sin informar"}</p><p><strong>Dolencia:</strong> {student?.Dolencia||"Sin informar"}</p><p><strong>Observaciones:</strong> {student?.Observaciones||"Sin informar"}</p></div><label className="text-sm font-semibold">Objetivo de la sesión<select className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3" name="Objetivo_Sesion" defaultValue="Fuerza">{["Fuerza","Hipertrofia","Resistencia","Acondicionamiento","Movilidad","Otro"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Objetivo libre (si elegís Otro)<Input maxLength={120} name="Objetivo_Otro"/></label><label className="text-sm font-semibold">Foco<Input defaultValue="Cuerpo completo" list="focus-options" maxLength={120} name="Foco" required/><datalist id="focus-options">{["Tren inferior","Tren superior","Cuerpo completo","Piernas","Glúteos","Pecho","Espalda","Brazos","Core"].map(x=><option key={x} value={x}/>)}</datalist></label><label className="text-sm font-semibold">Duración aproximada (minutos)<Input min={10} max={240} name="Duracion_Minutos" type="number"/></label><label className="text-sm font-semibold">Cantidad aproximada de bloques<Input min={1} max={12} name="Cantidad_Bloques" type="number"/></label><label className="text-sm font-semibold sm:col-span-2">Indicaciones adicionales<textarea className="min-h-28 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal" maxLength={2000} name="Indicaciones_Adicionales"/></label></section><p className="text-sm text-slate-600">La IA sólo propone ejercicios activos del catálogo. No realiza diagnósticos y la entrenadora debe revisar la propuesta.</p><Button disabled={busy||!students.length||Boolean(clarification)} type="submit">{busy?"Generando propuesta...":"Generar propuesta"}</Button></form>
 {clarification?<section className="space-y-4 rounded-2xl border border-violet-200 bg-violet-50 p-5"><h2 className="text-xl font-black">Necesito una aclaración</h2><p>{clarification.pregunta}</p><div className="grid gap-2">{clarification.opciones.map(option=><label className="flex min-h-11 items-center gap-2" key={option}><input name="clarification" onChange={()=>setAnswer(option)} type="radio"/> {option}</label>)}</div><label className="text-sm font-semibold">Otra indicación<textarea className="min-h-24 w-full rounded-xl border border-slate-300 bg-white p-3 font-normal" maxLength={1000} onChange={e=>setAnswer(e.target.value)} value={answer}/></label><Button disabled={busy||!answer.trim()} onClick={clarify}>{busy?"Generando propuesta...":"Continuar con esta aclaración"}</Button></section>:null}
 {proposal?<section className="space-y-4 rounded-2xl border border-cyan-200 bg-cyan-50 p-5"><div><p className="font-bold text-cyan-900">✨ Propuesta generada con IA · Revisá y ajustá antes de guardar.</p><h2 className="text-2xl font-black">{proposal.Titulo}</h2><p className="text-sm">{proposal.Notas_Generales}</p></div>{proposal.Bloques.map(block=><article className="rounded-xl bg-white p-4" key={block.Orden_Bloque}><h3 className="font-black">Bloque {block.Orden_Bloque} · {block.Tipo_Bloque}</h3>{block.Ejercicios.map(exercise=><div className="mt-3 border-t border-slate-100 pt-3" key={`${block.Orden_Bloque}-${exercise.Orden_Ejercicio}`}><p className="font-semibold">{catalog.find(x=>x.Catalogo_ID===exercise.Catalogo_ID)?.Ejercicio}</p><p className="text-sm text-slate-600">{exercise.Series} series · {exercise.Reps_Tiempo} · Descanso {exercise.Descanso} · RIR {exercise.RIR}</p></div>)}</article>)}<p className="text-sm font-semibold text-amber-900">{proposal.Advertencia_Revision}</p><div className="flex flex-wrap gap-3"><Button className="bg-slate-700" onClick={()=>{setProposal(null);setClarification(null);setAnswer("")}}>Descartar</Button><Button onClick={()=>setUseDraft(true)}>Usar propuesta</Button></div></section>:null}{error?<p className="rounded-lg bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</p>:null}</div>
}
