"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import type { Ejercicio } from "@/modules/ejercicios/domain/ejercicio";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function EjercicioForm({ejercicio}:{ejercicio?:Ejercicio}){const router=useRouter();const[error,setError]=useState("");const[saving,setSaving]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setSaving(true);const data=Object.fromEntries(new FormData(event.currentTarget).entries());const url=ejercicio?`/api/admin/ejercicios/${encodeURIComponent(ejercicio.Catalogo_ID)}`:"/api/admin/ejercicios";try{const response=await fetch(url,{method:ejercicio?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const payload=await response.json() as {ejercicio?:Ejercicio};if(!response.ok||!payload.ejercicio)throw new Error();router.replace(`/admin/ejercicios/${encodeURIComponent(payload.ejercicio.Catalogo_ID)}`);router.refresh();}catch{setError("Revisá los datos. Los videos deben ser URLs completas válidas.");}finally{setSaving(false);}}
 const initial=ejercicio??{Tipo_de_Ejercicio:"",Ejercicio:"",Video:"",Aclaraciones:"",Video_Adicional:""};
 return <form className="space-y-5" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-sm font-semibold text-slate-700">Tipo de ejercicio<Input defaultValue={initial.Tipo_de_Ejercicio} name="Tipo_de_Ejercicio" required/></label><label className="space-y-2 text-sm font-semibold text-slate-700">Nombre<Input defaultValue={initial.Ejercicio} name="Ejercicio" required/></label></div><label className="block space-y-2 text-sm font-semibold text-slate-700">Video principal<Input defaultValue={initial.Video} name="Video" placeholder="https://youtube.com/..." type="url"/></label><label className="block space-y-2 text-sm font-semibold text-slate-700">Video adicional<Input defaultValue={initial.Video_Adicional} name="Video_Adicional" placeholder="https://youtube.com/..." type="url"/></label><label className="block space-y-2 text-sm font-semibold text-slate-700">Aclaraciones<textarea className="min-h-28 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal outline-none focus:border-violet-500" defaultValue={initial.Aclaraciones} name="Aclaraciones"/></label>{error?<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>:null}<Button disabled={saving} type="submit">{saving?"Guardando…":ejercicio?"Guardar cambios":"Crear ejercicio"}</Button></form>;
}
