"use client";
import { useId,useRef,useState } from "react";
import type { Ejercicio } from "@/modules/ejercicios/domain/ejercicio";
import { filterExerciseCatalog } from "@/modules/ejercicios/application/filter-exercise-catalog";

export function ExerciseSearchCombobox({catalog,onSelect}:{catalog:Ejercicio[];onSelect:(exercise:Ejercicio)=>void}) {
  const id=useId(),inputRef=useRef<HTMLInputElement>(null);const[query,setQuery]=useState(""),[active,setActive]=useState(0),[open,setOpen]=useState(false);const results=filterExerciseCatalog(catalog,query,"",30);
  function select(exercise:Ejercicio){onSelect(exercise);setQuery("");setOpen(false);setActive(0);requestAnimationFrame(()=>inputRef.current?.focus())}
  return <div className="relative w-full"><label className="mb-1.5 block text-sm font-bold" htmlFor={`${id}-input`}>Agregar ejercicio</label><div className="relative"><span aria-hidden className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2">⌕</span><input aria-activedescendant={open&&results[active]?`${id}-option-${active}`:undefined} aria-autocomplete="list" aria-controls={`${id}-listbox`} aria-expanded={open&&Boolean(query.trim())} autoComplete="off" className="min-h-12 w-full rounded-xl border border-slate-300 bg-white py-2 pl-10 pr-4 outline-none focus:border-violet-600 focus:ring-4 focus:ring-violet-100" id={`${id}-input`} onChange={event=>{setQuery(event.target.value);setOpen(true);setActive(0)}} onFocus={()=>query.trim()&&setOpen(true)} onKeyDown={event=>{if(event.key==="Escape"){setOpen(false);return}if(!open||!results.length)return;if(event.key==="ArrowDown"){event.preventDefault();setActive(index=>(index+1)%results.length)}else if(event.key==="ArrowUp"){event.preventDefault();setActive(index=>(index-1+results.length)%results.length)}else if(event.key==="Enter"){event.preventDefault();select(results[active])}}} placeholder="Buscar ejercicio..." ref={inputRef} role="combobox" value={query}/></div>{!query.trim()?<p className="mt-2 text-xs text-slate-500">Escribí para buscar un ejercicio.</p>:null}{open&&query.trim()?<div className="absolute z-40 mt-1 max-h-64 w-full overflow-y-auto overscroll-contain rounded-xl border border-slate-200 bg-white p-1 shadow-xl" id={`${id}-listbox`} role="listbox">{results.map((exercise,index)=><button aria-selected={active===index} className={`block min-h-12 w-full rounded-lg px-3 py-2 text-left text-sm ${active===index?"bg-violet-50 ring-1 ring-violet-300":"hover:bg-slate-50"}`} id={`${id}-option-${index}`} key={exercise.Catalogo_ID} onMouseDown={event=>event.preventDefault()} onMouseEnter={()=>setActive(index)} onClick={()=>select(exercise)} role="option" type="button"><strong className="block">{exercise.Ejercicio}</strong><span className="block text-xs text-slate-500">{exercise.Tipo_de_Ejercicio}</span></button>)}{!results.length?<p className="px-3 py-4 text-sm text-slate-600">No encontramos ejercicios con esa búsqueda.</p>:null}</div>:null}<a className="brand-link mt-2 inline-flex min-h-11 items-center text-sm font-semibold" href="/admin/ejercicios/nuevo" rel="noopener noreferrer" target="_blank">Crear ejercicio en catálogo ↗</a></div>
}
