"use client";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import type { Alumno } from "@/modules/alumnos/domain/alumno";
import type { Ejercicio } from "@/modules/ejercicios/domain/ejercicio";
import type { RutinaEjercicio,RutinaSesion } from "@/modules/rutinas/domain/rutina";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
type Entry=Partial<RutinaEjercicio>&{key:string;Catalogo_ID:string;Tipo_Bloque:string;Instrumento_Alternativo:string;Reps_Tiempo:string;Series:string;Carga:string;Descanso:string;RIR:string;Observaciones:string};type Block={key:string;type:string;items:Entry[]};
const fresh=(id:string,type:string):Entry=>({key:crypto.randomUUID(),Catalogo_ID:id,Tipo_Bloque:type,Instrumento_Alternativo:"",Reps_Tiempo:"",Series:"",Carga:"",Descanso:"",RIR:"",Observaciones:""});

export function RutinaEditor({session,students,composition,catalog,createMode=false}:{session:RutinaSesion;students:Alumno[];composition:Array<{item:RutinaEjercicio;catalog:Ejercicio|null}>;catalog:Ejercicio[];createMode?:boolean}) {
 const router=useRouter();const initial=useMemo(()=>{const map=new Map<number,Block>();for(const{item}of composition){if(!map.has(item.Orden_Bloque))map.set(item.Orden_Bloque,{key:crypto.randomUUID(),type:item.Tipo_Bloque,items:[]});map.get(item.Orden_Bloque)!.items.push({...item,key:item.Rutina_Ejercicio_ID})}return[...map.entries()].sort((a,b)=>a[0]-b[0]).map(([,value])=>value)},[composition]);
 const[blocks,setBlocks]=useState(initial),[search,setSearch]=useState(""),[type,setType]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const types=[...new Set(catalog.map(item=>item.Tipo_de_Ejercicio))].sort();const choices=catalog.filter(item=>(!search||item.Ejercicio.toLowerCase().includes(search.toLowerCase()))&&(!type||item.Tipo_de_Ejercicio===type)).slice(0,24);
 function moveBlock(index:number,direction:number){const next=[...blocks],target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setBlocks(next)}
 function moveItem(blockIndex:number,itemIndex:number,direction:number){const next=structuredClone(blocks),target=itemIndex+direction;if(target<0||target>=next[blockIndex].items.length)return;[next[blockIndex].items[itemIndex],next[blockIndex].items[target]]=[next[blockIndex].items[target],next[blockIndex].items[itemIndex]];setBlocks(next)}
 function moveToBlock(blockIndex:number,itemIndex:number,targetIndex:number){if(blockIndex===targetIndex)return;const next=structuredClone(blocks),[item]=next[blockIndex].items.splice(itemIndex,1);item.Tipo_Bloque=next[targetIndex].type;next[targetIndex].items.push(item);setBlocks(next)}
 function patch(blockIndex:number,itemIndex:number,field:string,value:string){const next=structuredClone(blocks);next[blockIndex].items[itemIndex]={...next[blockIndex].items[itemIndex],[field]:value};setBlocks(next)}
 async function save(data:FormData){setBusy(true);setError("");setMessage("");const exercises=blocks.flatMap((block,blockIndex)=>block.items.map((item,itemIndex)=>({...item,key:undefined,Rutina_Ejercicio_ID:createMode?undefined:item.Rutina_Ejercicio_ID,Tipo_Bloque:block.type,Orden_Bloque:blockIndex+1,Orden_Ejercicio:itemIndex+1})));try{const response=await fetch(createMode?"/api/admin/rutinas/borrador":`/api/admin/rutinas/${session.Rutina_Sesion_ID}`,{method:createMode?"POST":"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({session:Object.fromEntries(data.entries()),exercises})}),payload=await response.json()as{rutina?:{session:{Rutina_Sesion_ID:string}}};if(!response.ok)throw new Error();if(createMode&&payload.rutina){router.replace(`/admin/rutinas/${payload.rutina.session.Rutina_Sesion_ID}`);return}setMessage("Rutina guardada.");router.refresh()}catch{setError("No se pudo guardar. Revisá los datos y ejercicios seleccionados.")}finally{setBusy(false)}}
 return <form action={save} className="space-y-7"><section className="surface grid gap-4 rounded-2xl p-5 sm:grid-cols-2"><label className="text-sm font-semibold">Alumno<select className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3" defaultValue={session.Alumno_ID} name="Alumno_ID">{students.map(student=><option key={student.Alumno_ID} value={student.Alumno_ID}>{student.Apellido}, {student.Nombre}</option>)}</select></label><label className="text-sm font-semibold">Día<Input defaultValue={session.Dia_Entrenamiento_Semana} name="Dia_Entrenamiento_Semana" pattern="Día [1-9][0-9]*" required/></label><label className="text-sm font-semibold">Fecha<Input defaultValue={session.Fecha} name="Fecha" required type="date"/></label><label className="text-sm font-semibold">Título<Input defaultValue={session.Titulo} name="Titulo" required/></label><label className="text-sm font-semibold sm:col-span-2">Notas<textarea className="min-h-24 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal focus:border-violet-600 focus:outline-none focus:ring-4 focus:ring-violet-100" defaultValue={session.Notas_Generales} name="Notas_Generales"/></label></section>
 <section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Composición</p><h2 className="text-2xl font-extrabold">Bloques y ejercicios</h2></div><Button onClick={()=>setBlocks([...blocks,{key:crypto.randomUUID(),type:`Bloque ${blocks.length+1}`,items:[]}])}>Nuevo bloque</Button></div>
 <div className="surface grid gap-3 rounded-2xl p-4 sm:grid-cols-2"><label className="text-sm font-semibold">Buscar ejercicio<Input onChange={event=>setSearch(event.target.value)} placeholder="Ej. sentadilla, remo…" value={search}/></label><label className="text-sm font-semibold">Filtrar por tipo<select className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3" onChange={event=>setType(event.target.value)} value={type}><option value="">Todos</option>{types.map(value=><option key={value}>{value}</option>)}</select></label><p className="text-xs text-slate-500 sm:col-span-2">{choices.length} resultados visibles. Refiná la búsqueda para encontrar más rápido.</p></div>
 {blocks.map((block,blockIndex)=><article className="surface space-y-4 rounded-2xl border-l-4 border-l-violet-700 p-4 sm:p-5" key={block.key}><header className="flex flex-wrap items-center gap-2"><span className="flex size-8 items-center justify-center rounded-full bg-violet-700 text-sm font-bold text-white">{blockIndex+1}</span><Input aria-label={`Nombre del bloque ${blockIndex+1}`} className="min-w-48 flex-1 font-bold" onChange={event=>{const next=structuredClone(blocks);next[blockIndex].type=event.target.value;setBlocks(next)}} value={block.type}/><button aria-label="Mover bloque arriba" className="min-h-11 min-w-11 rounded-lg border border-slate-300" onClick={()=>moveBlock(blockIndex,-1)} type="button">↑</button><button aria-label="Mover bloque abajo" className="min-h-11 min-w-11 rounded-lg border border-slate-300" onClick={()=>moveBlock(blockIndex,1)} type="button">↓</button></header>
 {block.items.map((item,itemIndex)=>{const master=composition.find(entry=>entry.item.Rutina_Ejercicio_ID===item.Rutina_Ejercicio_ID)?.catalog??catalog.find(entry=>entry.Catalogo_ID===item.Catalogo_ID);return <div className="rounded-2xl border border-slate-200 bg-white p-4" key={item.key}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-violet-700">Ejercicio {itemIndex+1}</p><h3 className="font-extrabold">{master?.Ejercicio??"Ejercicio inexistente"}</h3><p className="text-xs text-slate-500">{master?.Tipo_de_Ejercicio} · {master&&!master.Activo?"Archivado":"Activo"}</p></div><button className="min-h-11 rounded-lg px-2 text-sm font-bold text-red-700" onClick={()=>{const next=structuredClone(blocks);next[blockIndex].items.splice(itemIndex,1);setBlocks(next)}} type="button">Quitar</button></div>
 <div className="mt-4 grid gap-3 sm:grid-cols-3">{[["Series","Series"],["Reps_Tiempo","Reps / tiempo"],["Carga","Carga"]].map(([field,label])=><label className="text-xs font-semibold" key={field}>{label}<Input inputMode={field==="Series"?"numeric":"text"} onChange={event=>patch(blockIndex,itemIndex,field,event.target.value)} value={String(item[field as keyof Entry]??"")}/></label>)}</div>
 <details className="mt-3 rounded-xl bg-slate-50"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between px-3 text-sm font-bold text-violet-700">Más opciones <span aria-hidden>＋</span></summary><div className="grid gap-3 border-t border-slate-200 p-3 sm:grid-cols-2">{[["RIR","RIR"],["Descanso","Descanso"],["Instrumento_Alternativo","Instrumento alternativo"],["Observaciones","Observaciones"]].map(([field,label])=><label className="text-xs font-semibold" key={field}>{label}<Input onChange={event=>patch(blockIndex,itemIndex,field,event.target.value)} value={String(item[field as keyof Entry]??"")}/></label>)}<label className="text-xs font-semibold">Mover a bloque<select className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3" onChange={event=>moveToBlock(blockIndex,itemIndex,Number(event.target.value))} value={blockIndex}>{blocks.map((candidate,index)=><option key={candidate.key} value={index}>{index+1} · {candidate.type}</option>)}</select></label><div className="flex items-end gap-2"><button className="min-h-11 flex-1 rounded-xl border border-slate-300 font-bold" onClick={()=>moveItem(blockIndex,itemIndex,-1)} type="button">↑ Subir</button><button className="min-h-11 flex-1 rounded-xl border border-slate-300 font-bold" onClick={()=>moveItem(blockIndex,itemIndex,1)} type="button">↓ Bajar</button></div></div></details></div>})}
 <div className="rounded-xl border border-dashed border-violet-200 bg-violet-50/60 p-3"><p className="mb-2 text-sm font-bold">Agregar ejercicio</p><div className="grid max-h-56 gap-2 overflow-y-auto sm:grid-cols-2">{choices.map(choice=><button className="min-h-11 rounded-xl border border-slate-200 bg-white px-3 py-2 text-left text-sm transition hover:border-violet-400 hover:bg-violet-50" key={choice.Catalogo_ID} onClick={()=>{const next=structuredClone(blocks);next[blockIndex].items.push(fresh(choice.Catalogo_ID,next[blockIndex].type));setBlocks(next)}} type="button"><strong className="block">{choice.Ejercicio}</strong><span className="text-xs text-slate-500">{choice.Tipo_de_Ejercicio}</span></button>)}</div>{!choices.length?<p className="text-sm text-slate-600">No hay ejercicios activos que coincidan.</p>:null}<a className="brand-link mt-3 inline-flex min-h-11 items-center text-sm font-semibold" href="/admin/ejercicios/nuevo" rel="noopener noreferrer" target="_blank">Crear ejercicio en catálogo ↗</a></div></article>)}</section>
 {message?<p className="rounded-xl bg-emerald-50 p-3 text-emerald-800" role="status">✓ {message}</p>:null}{error?<p className="rounded-xl bg-red-50 p-3 text-red-800" role="alert">{error}</p>:null}<div className="sticky bottom-3 z-20 rounded-2xl bg-white/90 p-3 shadow-lg backdrop-blur"><Button className="w-full" disabled={busy} type="submit">{busy?"Guardando…":createMode?"Guardar rutina":"Guardar rutina completa"}</Button></div></form>;
}
