import assert from "node:assert/strict";
import { after,describe,it } from "node:test";
import { google } from "googleapis";
import { GoogleSheetsEjercicioRepository } from "@/infrastructure/sheets/repositories";
import { SHEET_NAMES } from "@/infrastructure/sheets/sheet-names";
import { createEjercicioAdminService } from "@/modules/ejercicios/application/ejercicio-admin-service";

let createdId="";
after(async()=>{if(!createdId)return;const spreadsheetId=process.env.GOOGLE_SHEETS_SPREADSHEET_ID;assert.ok(spreadsheetId);const auth=new google.auth.GoogleAuth({scopes:["https://www.googleapis.com/auth/spreadsheets"]});const api=google.sheets({version:"v4",auth});const response=await api.spreadsheets.values.get({spreadsheetId,range:`'${SHEET_NAMES.catalogoEjercicios}'!A2:A`});const rows=response.data.values??[];const ranges=rows.map((row,index)=>({id:String(row[0]??""),range:`'${SHEET_NAMES.catalogoEjercicios}'!A${index+2}:G${index+2}`})).filter(row=>row.id===createdId).map(row=>row.range);if(ranges.length)await api.spreadsheets.values.batchClear({spreadsheetId,requestBody:{ranges}});});

describe("real exercise catalog integration",()=>{it("reads inherited data and performs a complete test lifecycle",async()=>{const repository=new GoogleSheetsEjercicioRepository();const service=createEjercicioAdminService(repository);const existing=await repository.findAll({includeArchived:true});assert.ok(existing.length>0);assert.ok(existing.some(item=>!item.Catalogo_ID.match(/^[0-9a-f-]{36}$/i)),"Expected inherited non-UUID IDs");const suffix=Date.now();const created=await service.create({Tipo_de_Ejercicio:"ARU_TEST_TIPO",Ejercicio:`ARU_TEST_EJERCICIO_${suffix}`,Video:"https://www.youtube.com/watch?v=dQw4w9WgXcQ",Aclaraciones:"ARU_TEST_CREATE",Video_Adicional:""});createdId=created.Catalogo_ID;assert.match(createdId,/^[0-9a-f-]{36}$/);assert.equal((await service.get(createdId)).Ejercicio,created.Ejercicio);assert.equal((await service.list({search:String(suffix),type:"ARU_TEST_TIPO",status:"active"})).length,1);const updated=await service.update(createdId,{Tipo_de_Ejercicio:"ARU_TEST_TIPO",Ejercicio:`ARU_TEST_EDITADO_${suffix}`,Video:"",Aclaraciones:"ARU_TEST_UPDATE",Video_Adicional:"https://youtu.be/dQw4w9WgXcQ"});assert.equal(updated.Catalogo_ID,createdId);assert.equal((await service.setActive(createdId,false)).Activo,false);assert.equal((await service.list({search:String(suffix),status:"archived"})).length,1);assert.equal((await service.setActive(createdId,true)).Activo,true);});});
