import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { after, describe, it } from "node:test";
import { google } from "googleapis";
import { getFirebaseAdminAuth } from "@/infrastructure/firebase/admin";
import { GoogleSheetsAlumnoRepository, GoogleSheetsCobroRepository, GoogleSheetsUsuarioRepository } from "@/infrastructure/sheets/repositories";
import { SHEET_NAMES } from "@/infrastructure/sheets/sheet-names";
import { AuthService } from "@/modules/auth/application/auth-service";
import { AuthError } from "@/modules/auth/domain/errors";
import { createCobroAdminService } from "@/modules/cobros/application/cobro-admin-service";
const alumnoId=randomUUID(),adminUserId=randomUUID(),studentUserId=randomUUID(),cobroIds:string[]=[];const firebaseUids:string[]=[];
async function clearAll(){const specs=[[SHEET_NAMES.cobros,cobroIds,"G"],[SHEET_NAMES.usuarios,[adminUserId,studentUserId],"F"],[SHEET_NAMES.alumnos,[alumnoId],"K"]]as const;const spreadsheetId=process.env.GOOGLE_SHEETS_SPREADSHEET_ID;assert.ok(spreadsheetId);const api=google.sheets({version:"v4",auth:new google.auth.GoogleAuth({scopes:["https://www.googleapis.com/auth/spreadsheets"]})});const response=await api.spreadsheets.values.batchGet({spreadsheetId,ranges:specs.map(([sheet])=>`'${sheet}'!A2:A`)});const ranges:string[]=[];specs.forEach(([sheet,ids,end],table)=>(response.data.valueRanges?.[table]?.values??[]).forEach((row,index)=>{if(ids.includes(String(row[0]??"")as never))ranges.push(`'${sheet}'!A${index+2}:${end}${index+2}`);}));if(ranges.length)await api.spreadsheets.values.batchClear({spreadsheetId,requestBody:{ranges}});}
after(async()=>{for(const uid of firebaseUids)await getFirebaseAdminAuth().deleteUser(uid).catch(()=>undefined);await clearAll();});
describe("real charges integration",()=>{it("persists, filters, summarizes and enforces ADMIN without changing access",async()=>{const firebase=getFirebaseAdminAuth(),alumnos=new GoogleSheetsAlumnoRepository(),cobros=new GoogleSheetsCobroRepository(),users=new GoogleSheetsUsuarioRepository(),service=createCobroAdminService({cobros,alumnos});const suffix=`${Date.now()}.${randomUUID().slice(0,8)}`,adminEmail=`aru.cobros.admin.${suffix}@example.com`,studentEmail=`aru.cobros.student.${suffix}@example.com`,adminPassword=`Aru!${randomBytes(24).toString("base64url")}`,studentPassword=`Aru!${randomBytes(24).toString("base64url")}`;
await alumnos.create({Alumno_ID:alumnoId,Documento:`ARU_TEST_${suffix}`,Nombre:"ARU_TEST",Apellido:"COBROS",Fecha_Nacimiento:"1990-01-01",Celular:"000",Mail:studentEmail,Fecha_Alta:"2026-08-15",Objetivo:"ARU_TEST",Dolencia:"",Observaciones:""});const adminFirebase=await firebase.createUser({email:adminEmail,password:adminPassword}),studentFirebase=await firebase.createUser({email:studentEmail,password:studentPassword});firebaseUids.push(adminFirebase.uid,studentFirebase.uid);await users.create({Usuario_ID:adminUserId,Alumno_ID:null,Email:adminEmail,Rol:"ADMIN",Activo:true,UID_Auth:adminFirebase.uid});await users.create({Usuario_ID:studentUserId,Alumno_ID:alumnoId,Email:studentEmail,Rol:"ALUMNO",Activo:true,UID_Auth:studentFirebase.uid});const beforeAccess=await users.findById(studentUserId);assert.equal(beforeAccess?.Activo,true);
const pending=await service.create({Alumno_ID:alumnoId,Mes_Abonado:"2026-08",Fecha_Pago:null,Importe:10000,Estado_Pago:"PENDIENTE",Medio_Pago:"TRANSFERENCIA"});cobroIds.push(pending.Cobro_ID);assert.equal((await cobros.findById(pending.Cobro_ID))?.Importe,10000);const paid=await service.update(pending.Cobro_ID,{Alumno_ID:alumnoId,Mes_Abonado:"2026-08",Fecha_Pago:"2026-08-15",Importe:12000,Estado_Pago:"PAGADO",Medio_Pago:"EFECTIVO"});assert.equal(paid.Cobro_ID,pending.Cobro_ID);const listed=await service.list({search:"ARU_TEST COBROS",month:"2026-08",status:"PAGADO"});assert.equal(listed.entries.length,1);assert.equal(listed.summary.registrados,1);assert.equal(listed.summary.totalCobrado,12000);assert.equal(listed.summary.pendientes,0);assert.equal((await service.recentForStudent(alumnoId))[0].Cobro_ID,pending.Cobro_ID);assert.equal((await users.findById(studentUserId))?.Activo,beforeAccess?.Activo);
const apiKey=process.env.NEXT_PUBLIC_FIREBASE_API_KEY;assert.ok(apiKey);async function login(email:string,password:string){const response=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${encodeURIComponent(apiKey!)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password,returnSecureToken:true})});assert.equal(response.ok,true);return response.json()as Promise<{idToken:string}>;}const authService=new AuthService(firebase,users),adminAuth=await authService.createSession((await login(adminEmail,adminPassword)).idToken),studentAuth=await authService.createSession((await login(studentEmail,studentPassword)).idToken);assert.equal(adminAuth.user.role,"ADMIN");await assert.rejects(()=>authService.resolveSession(studentAuth.cookie,"ADMIN"),(error:unknown)=>error instanceof AuthError&&error.code==="ROLE_FORBIDDEN");
const baseUrl=process.env.ARU_TEST_BASE_URL;if(baseUrl){async function webSession(idToken:string){const response=await fetch(`${baseUrl}/api/auth/session`,{method:"POST",headers:{origin:baseUrl,"content-type":"application/json"},body:JSON.stringify({idToken})});assert.equal(response.status,200);const cookie=response.headers.getSetCookie()[0]?.split(";",1)[0];assert.ok(cookie);return cookie;}const adminCookie=await webSession((await login(adminEmail,adminPassword)).idToken),studentCookie=await webSession((await login(studentEmail,studentPassword)).idToken);const page=await fetch(`${baseUrl}/admin/cobros?mes=2026-08`,{headers:{cookie:adminCookie}});assert.equal(page.status,200);assert.match(await page.text(),/ARU_TEST/);const studentAttempt=await fetch(`${baseUrl}/api/admin/cobros`,{method:"POST",headers:{cookie:studentCookie,origin:baseUrl,"content-type":"application/json"},body:JSON.stringify({Alumno_ID:alumnoId,Mes_Abonado:"2026-09",Fecha_Pago:null,Importe:1,Estado_Pago:"PENDIENTE",Medio_Pago:"EFECTIVO"})});assert.equal(studentAttempt.status,403);const ficha=await fetch(`${baseUrl}/admin/alumnos/${alumnoId}`,{headers:{cookie:adminCookie}});assert.equal(ficha.status,200);assert.match(await ficha.text(),/Cobros/);}
});});
