import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { after, describe, it } from "node:test";
import { google } from "googleapis";
import { getFirebaseAdminAuth } from "@/infrastructure/firebase/admin";
import { GoogleSheetsEjercicioRepository, GoogleSheetsRutinaEjercicioRepository, GoogleSheetsRutinaSesionRepository, GoogleSheetsUsuarioRepository } from "@/infrastructure/sheets/repositories";
import { SHEET_NAMES } from "@/infrastructure/sheets/sheet-names";
import { AuthService } from "@/modules/auth/application/auth-service";
import { AuthError } from "@/modules/auth/domain/errors";
import { createEntrenamientoAlumnoService } from "@/modules/entrenamientos/application/entrenamiento-alumno-service";
import { EntrenamientoAlumnoError } from "@/modules/entrenamientos/application/errors";

const alumnoId = randomUUID(), otherAlumnoId = randomUUID(), userId = randomUUID(), catalogId = randomUUID();
const routineIds = Array.from({ length: 5 }, () => randomUUID());
const itemIds = [randomUUID(), randomUUID()];
let firebaseUid = "";
async function clear(sheet: string, ids: string[], end: string) { const spreadsheetId = process.env.GOOGLE_SHEETS_SPREADSHEET_ID; assert.ok(spreadsheetId); const api = google.sheets({ version: "v4", auth: new google.auth.GoogleAuth({ scopes: ["https://www.googleapis.com/auth/spreadsheets"] }) }); const response = await api.spreadsheets.values.get({ spreadsheetId, range: `'${sheet}'!A2:A` }); const ranges = (response.data.values ?? []).map((row, index) => ({ id: String(row[0] ?? ""), range: `'${sheet}'!A${index + 2}:${end}${index + 2}` })).filter((row) => ids.includes(row.id)).map((row) => row.range); if (ranges.length) await api.spreadsheets.values.batchClear({ spreadsheetId, requestBody: { ranges } }); }
after(async () => { if (firebaseUid) await getFirebaseAdminAuth().deleteUser(firebaseUid).catch(() => undefined); await clear(SHEET_NAMES.rutinaEjercicio, itemIds, "M"); await clear(SHEET_NAMES.rutinaSesion, routineIds, "I"); await clear(SHEET_NAMES.usuarios, [userId], "F"); await clear(SHEET_NAMES.catalogoEjercicios, [catalogId], "G"); });

describe("real ALUMNO training experience", () => { it("logs in, isolates ownership, reads archived details and persists completion/reversion", async () => {
  const firebase = getFirebaseAdminAuth(), users = new GoogleSheetsUsuarioRepository(), sessions = new GoogleSheetsRutinaSesionRepository(), items = new GoogleSheetsRutinaEjercicioRepository(), catalog = new GoogleSheetsEjercicioRepository();
  const service = createEntrenamientoAlumnoService({ sessions, items, catalog, now: () => new Date("2026-08-15T15:00:00Z") });
  const suffix = `${Date.now()}.${randomUUID().slice(0, 8)}`, email = `aru.etapa8.${suffix}@example.com`, password = `Aru!${randomBytes(24).toString("base64url")}`;
  const firebaseUser = await firebase.createUser({ email, password }); firebaseUid = firebaseUser.uid;
  await users.create({ Usuario_ID: userId, Alumno_ID: alumnoId, Email: email, Rol: "ALUMNO", Activo: true, UID_Auth: firebaseUid });
  await catalog.create({ Catalogo_ID: catalogId, Tipo_de_Ejercicio: "ARU_TEST_TIPO", Ejercicio: `ARU_TEST_EJERCICIO_${suffix}`, Video: "https://example.com/video", Aclaraciones: "ARU_TEST_ACLARACION", Video_Adicional: "https://example.com/adicional", Activo: false });
  const makeSession = (id: string, owner: string, date: string, title: string, completed = false) => ({ Rutina_Sesion_ID: id, Alumno_ID: owner, Dia_Entrenamiento_Semana: "Día 1" as const, Fecha: date, Titulo: title, Notas_Generales: "ARU_TEST_NOTAS", Plantilla_Sesion_Origen_ID: null, Entrenamiento_Completado: completed, Fecha_Completado: completed ? date : null });
  await sessions.create(makeSession(routineIds[0], alumnoId, "2026-08-10", "ARU_TEST_VENCIDA")); await sessions.create(makeSession(routineIds[1], alumnoId, "2026-08-16", "ARU_TEST_PROXIMA")); await sessions.create(makeSession(routineIds[2], alumnoId, "2026-08-20", "ARU_TEST_COMPLETADA", true)); await sessions.create(makeSession(routineIds[3], otherAlumnoId, "2026-08-15", "ARU_TEST_AJENA")); await sessions.create(makeSession(routineIds[4], alumnoId, "2026-08-21", "ARU_TEST_VACIA"));
  const makeItem = (id: string, block: number, order: number) => ({ Rutina_Ejercicio_ID: id, Rutina_Sesion_ID: routineIds[1], Catalogo_ID: catalogId, Tipo_Bloque: `ARU_TEST_BLOQUE_${block}`, Orden_Bloque: block, Orden_Ejercicio: order, Instrumento_Alternativo: "Banda", Reps_Tiempo: "10", Series: "3", Carga: "5 kg", Descanso: "30 s", RIR: "2", Observaciones: "ARU_TEST_INDICACION" });
  await items.create(makeItem(itemIds[0], 2, 2)); await items.create(makeItem(itemIds[1], 1, 3));
  const apiKey = process.env.NEXT_PUBLIC_FIREBASE_API_KEY; assert.ok(apiKey); const login = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${encodeURIComponent(apiKey)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password, returnSecureToken: true }) }); assert.equal(login.ok, true); const token = await login.json() as { idToken: string }; const authService = new AuthService(firebase, users); const auth = await authService.createSession(token.idToken); assert.equal(auth.user.role, "ALUMNO"); assert.equal(auth.user.alumnoId, alumnoId); await assert.rejects(() => authService.resolveSession(auth.cookie, "ADMIN"), (error: unknown) => error instanceof AuthError && error.code === "ROLE_FORBIDDEN");
  const list = await service.list(auth.user.alumnoId!); assert.equal(list.next?.Rutina_Sesion_ID, routineIds[1]); assert.equal([...list.upcoming, ...list.previous].some(({ session }) => session.Rutina_Sesion_ID === routineIds[3]), false); assert.equal(list.previous.some(({ session, state }) => session.Rutina_Sesion_ID === routineIds[0] && state === "pendiente"), true);
  const detail = await service.detail(auth.user.alumnoId!, routineIds[1]); assert.deepEqual(detail.blocks.map((block) => block.order), [1, 2]); assert.equal(detail.blocks[0].exercises[0].catalog?.Activo, false); assert.equal(detail.blocks[0].exercises[0].catalog?.Video_Adicional, "https://example.com/adicional"); assert.deepEqual((await service.detail(auth.user.alumnoId!, routineIds[4])).blocks, []); await assert.rejects(() => service.detail(auth.user.alumnoId!, routineIds[3]), (error: unknown) => error instanceof EntrenamientoAlumnoError && error.code === "RUTINA_FORBIDDEN");
  const completed = await service.setCompleted(auth.user.alumnoId!, routineIds[1], true); assert.equal(completed.Fecha_Completado, "2026-08-15"); assert.equal((await sessions.findById(routineIds[1]))?.Entrenamiento_Completado, true); assert.equal((await service.detail(auth.user.alumnoId!, routineIds[1])).session.Entrenamiento_Completado, true); const reverted = await service.setCompleted(auth.user.alumnoId!, routineIds[1], false); assert.equal(reverted.Fecha_Completado, null); assert.equal((await sessions.findById(routineIds[1]))?.Entrenamiento_Completado, false); await assert.rejects(() => service.setCompleted(auth.user.alumnoId!, routineIds[3], true), (error: unknown) => error instanceof EntrenamientoAlumnoError && error.code === "RUTINA_FORBIDDEN");
  const baseUrl = process.env.ARU_TEST_BASE_URL;
  if (baseUrl) {
    const sessionResponse = await fetch(`${baseUrl}/api/auth/session`, { method: "POST", headers: { "content-type": "application/json", origin: baseUrl }, body: JSON.stringify({ idToken: token.idToken }), redirect: "manual" }); assert.equal(sessionResponse.status, 200); const cookie = sessionResponse.headers.getSetCookie()[0]?.split(";", 1)[0]; assert.ok(cookie); assert.equal((await sessionResponse.json() as { role: string }).role, "ALUMNO");
    const listPage = await fetch(`${baseUrl}/entrenamientos`, { headers: { cookie }, redirect: "manual" }); assert.equal(listPage.status, 200); const listHtml = await listPage.text(); assert.match(listHtml, /ARU_TEST_PROXIMA/); assert.doesNotMatch(listHtml, /ARU_TEST_AJENA/);
    const ownPage = await fetch(`${baseUrl}/entrenamientos/${routineIds[1]}`, { headers: { cookie }, redirect: "manual" }); assert.equal(ownPage.status, 200); assert.match(await ownPage.text(), /ARU_TEST_EJERCICIO/);
    const foreignPage = await fetch(`${baseUrl}/entrenamientos/${routineIds[3]}`, { headers: { cookie }, redirect: "manual" }); assert.equal(foreignPage.status, 404);
    const mark = await fetch(`${baseUrl}/api/alumno/entrenamientos/${routineIds[1]}/estado`, { method: "PATCH", headers: { cookie, origin: baseUrl, "content-type": "application/json" }, body: JSON.stringify({ completed: true }) }); assert.equal(mark.status, 200); assert.equal((await sessions.findById(routineIds[1]))?.Entrenamiento_Completado, true);
    const foreignMark = await fetch(`${baseUrl}/api/alumno/entrenamientos/${routineIds[3]}/estado`, { method: "PATCH", headers: { cookie, origin: baseUrl, "content-type": "application/json" }, body: JSON.stringify({ completed: true }) }); assert.equal(foreignMark.status, 403);
    const unmark = await fetch(`${baseUrl}/api/alumno/entrenamientos/${routineIds[1]}/estado`, { method: "PATCH", headers: { cookie, origin: baseUrl, "content-type": "application/json" }, body: JSON.stringify({ completed: false }) }); assert.equal(unmark.status, 200); assert.equal((await sessions.findById(routineIds[1]))?.Fecha_Completado, null);
    const logout = await fetch(`${baseUrl}/api/auth/logout`, { method: "POST", headers: { cookie, origin: baseUrl } }); assert.equal(logout.status, 204); const rejected = await fetch(`${baseUrl}/entrenamientos`, { redirect: "manual" }); assert.equal(rejected.status, 307);
  }
}); });
