import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { after, describe, it } from "node:test";
import { google } from "googleapis";
import { getFirebaseAdminAuth } from "@/infrastructure/firebase/admin";
import { GoogleSheetsPlantillaEjercicioRepository, GoogleSheetsUsuarioRepository } from "@/infrastructure/sheets/repositories";
import { SHEET_NAMES } from "@/infrastructure/sheets/sheet-names";

const baseUrl=process.env.ARU_TEST_BASE_URL;const spreadsheetId=process.env.GOOGLE_SHEETS_SPREADSHEET_ID;const apiKey=process.env.NEXT_PUBLIC_FIREBASE_API_KEY;
const tracked=new Map<string,string[]>();const firebaseUids:string[]=[];let quotaStep="inicio";
function track(sheet:string,id:string){tracked.set(sheet,[...(tracked.get(sheet)??[]),id]);return id;}
async function cleanup(){for(const uid of firebaseUids)await getFirebaseAdminAuth().deleteUser(uid).catch(()=>undefined);if(!spreadsheetId)return;const specs=[[SHEET_NAMES.registroProgreso,"H"],[SHEET_NAMES.rutinaEjercicio,"M"],[SHEET_NAMES.rutinaSesion,"I"],[SHEET_NAMES.plantillaEjercicio,"L"],[SHEET_NAMES.plantillaSesion,"G"],[SHEET_NAMES.cobros,"G"],[SHEET_NAMES.usuarios,"F"],[SHEET_NAMES.alumnos,"K"],[SHEET_NAMES.catalogoEjercicios,"G"]]as const;const sheets=google.sheets({version:"v4",auth:new google.auth.GoogleAuth({scopes:["https://www.googleapis.com/auth/spreadsheets"]})});const response=await sheets.spreadsheets.values.batchGet({spreadsheetId,ranges:specs.map(([sheet])=>`'${sheet}'!A2:A`)});const ranges:string[]=[];specs.forEach(([sheet,end],index)=>(response.data.valueRanges?.[index]?.values??[]).forEach((row,rowIndex)=>{if((tracked.get(sheet)??[]).includes(String(row[0]??"")))ranges.push(`'${sheet}'!A${rowIndex+2}:${end}${rowIndex+2}`);}));if(ranges.length)await sheets.spreadsheets.values.batchClear({spreadsheetId,requestBody:{ranges}});}
after(cleanup);
async function request(path:string,init:RequestInit={}){const response=await fetch(`${baseUrl}${path}`,init);const body=await response.text();if(response.status===429||/quota|RESOURCE_EXHAUSTED/i.test(body))throw new Error(`GOOGLE_SHEETS_QUOTA_AT:${quotaStep}`);return{response,body,json:<T>()=>JSON.parse(body)as T};}
async function firebaseLogin(email:string,password:string){const response=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${encodeURIComponent(apiKey!)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password,returnSecureToken:true})});assert.equal(response.status,200);return response.json()as Promise<{idToken:string}>;}
async function webSession(email:string,password:string){const token=await firebaseLogin(email,password);const result=await request("/api/auth/session",{method:"POST",headers:{origin:baseUrl!,"content-type":"application/json"},body:JSON.stringify({idToken:token.idToken})});assert.equal(result.response.status,200);const cookie=result.response.headers.getSetCookie()[0]?.split(";",1)[0];assert.ok(cookie);return cookie;}
function adminHeaders(cookie:string){return{cookie,origin:baseUrl!,"content-type":"application/json"};}

describe("focused ADMIN -> ALUMNO -> ADMIN MVP flow",()=>{it("integrates the approved modules without touching real data",{timeout:180_000},async()=>{assert.ok(baseUrl);assert.ok(spreadsheetId);assert.ok(apiKey);const suffix=`${Date.now()}_${randomUUID().slice(0,8)}`,adminEmail=`aru_test_admin_${suffix}@example.com`,studentEmail=`aru_test_alumno_${suffix}@example.com`,adminPassword=`Aru!${randomBytes(24).toString("base64url")}`,studentPassword=`Aru!${randomBytes(24).toString("base64url")}`;const firebase=getFirebaseAdminAuth(),users=new GoogleSheetsUsuarioRepository();
quotaStep="preparar administrador";const adminFirebase=await firebase.createUser({email:adminEmail,password:adminPassword});firebaseUids.push(adminFirebase.uid);const adminUserId=track(SHEET_NAMES.usuarios,randomUUID());await users.create({Usuario_ID:adminUserId,Alumno_ID:null,Email:adminEmail,Rol:"ADMIN",Activo:true,UID_Auth:adminFirebase.uid});const adminCookie=await webSession(adminEmail,adminPassword);
quotaStep="crear alumno";let result=await request("/api/admin/alumnos",{method:"POST",headers:adminHeaders(adminCookie),body:JSON.stringify({Documento:`ARU_TEST_${suffix}`,Nombre:"ARU_TEST",Apellido:"E2E",Fecha_Nacimiento:"1990-01-01",Celular:"000",Mail:studentEmail,Fecha_Alta:"2026-08-15",Objetivo:"ARU_TEST integración",Dolencia:"",Observaciones:"ARU_TEST"})});assert.equal(result.response.status,201);const alumnoId=track(SHEET_NAMES.alumnos,result.json<{alumno:{Alumno_ID:string}}>().alumno.Alumno_ID);
quotaStep="habilitar acceso";result=await request(`/api/admin/alumnos/${alumnoId}/acceso`,{method:"POST",headers:adminHeaders(adminCookie),body:JSON.stringify({Email:studentEmail})});assert.equal(result.response.status,201);const access=result.json<{access:{Usuario_ID:string;UID_Auth:string}}>().access;track(SHEET_NAMES.usuarios,access.Usuario_ID);firebaseUids.push(access.UID_Auth);
quotaStep="establecer contraseña";const resetLink=await firebase.generatePasswordResetLink(studentEmail);const oobCode=new URL(resetLink).searchParams.get("oobCode");assert.ok(oobCode);const reset=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:resetPassword?key=${encodeURIComponent(apiKey)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({oobCode,newPassword:studentPassword})});assert.equal(reset.status,200);
quotaStep="registrar cobro";result=await request("/api/admin/cobros",{method:"POST",headers:adminHeaders(adminCookie),body:JSON.stringify({Alumno_ID:alumnoId,Mes_Abonado:"2026-08",Fecha_Pago:"2026-08-15",Importe:12345,Estado_Pago:"PAGADO",Medio_Pago:"TRANSFERENCIA"})});assert.equal(result.response.status,201);track(SHEET_NAMES.cobros,result.json<{cobro:{Cobro_ID:string}}>().cobro.Cobro_ID);
quotaStep="consultar catálogo";result=await request("/admin/ejercicios",{headers:{cookie:adminCookie}});assert.equal(result.response.status,200);assert.match(result.body,/Catálogo/i);
const catalogIds:string[]=[];for(const index of [1,2]){quotaStep=`crear ejercicio ${index}`;result=await request("/api/admin/ejercicios",{method:"POST",headers:adminHeaders(adminCookie),body:JSON.stringify({Tipo_de_Ejercicio:"ARU_TEST",Ejercicio:`ARU_TEST_EJERCICIO_${index}_${suffix}`,Video:`https://example.com/aru-test-${index}`,Aclaraciones:"ARU_TEST",Video_Adicional:""})});assert.equal(result.response.status,201);catalogIds.push(track(SHEET_NAMES.catalogoEjercicios,result.json<{ejercicio:{Catalogo_ID:string}}>().ejercicio.Catalogo_ID));}
quotaStep="crear plantilla";result=await request("/api/admin/plantillas",{method:"POST",headers:adminHeaders(adminCookie),body:JSON.stringify({Nombre_Plantilla:`ARU_TEST_PLANTILLA_${suffix}`,Objetivo:"ARU_TEST",Grupo_Muscular_1:"General",Grupo_Muscular_2:"",Notas:"ARU_TEST original"})});assert.equal(result.response.status,201);const templateId=track(SHEET_NAMES.plantillaSesion,result.json<{plantilla:{Plantilla_Sesion_ID:string}}>().plantilla.Plantilla_Sesion_ID);
quotaStep="armar plantilla";result=await request(`/api/admin/plantillas/${templateId}`,{method:"PUT",headers:adminHeaders(adminCookie),body:JSON.stringify({session:{Nombre_Plantilla:`ARU_TEST_PLANTILLA_${suffix}`,Objetivo:"ARU_TEST",Grupo_Muscular_1:"General",Grupo_Muscular_2:"",Notas:"ARU_TEST original"},exercises:catalogIds.map((Catalogo_ID,index)=>({Tipo_Bloque:index===0?"Entrada en calor":"Fuerza",Orden_Bloque:index+1,Orden_Ejercicio:1,Catalogo_ID,Reps_Tiempo:"10",Series:"3",Carga:"20 kg",Descanso:"60 s",RIR:"2",Observaciones:"ARU_TEST original"}))})});assert.equal(result.response.status,200);const templateItems=result.json<{plantilla:{exercises:{Plantilla_Ejercicio_ID:string}[]}}>().plantilla.exercises;templateItems.forEach(item=>track(SHEET_NAMES.plantillaEjercicio,item.Plantilla_Ejercicio_ID));
quotaStep="crear rutina";result=await request("/api/admin/rutinas",{method:"POST",headers:adminHeaders(adminCookie),body:JSON.stringify({Alumno_ID:alumnoId,Plantilla_Sesion_ID:templateId,Dia_Entrenamiento_Semana:"Día 1",Fecha:"2026-08-16",Titulo:`ARU_TEST_RUTINA_${suffix}`,Notas_Generales:"ARU_TEST clon"})});assert.equal(result.response.status,201);const routine=result.json<{rutina:{session:{Rutina_Sesion_ID:string};exercises:Array<Record<string,unknown>&{Rutina_Ejercicio_ID:string}>}}>().rutina;const routineId=track(SHEET_NAMES.rutinaSesion,routine.session.Rutina_Sesion_ID);routine.exercises.forEach(item=>track(SHEET_NAMES.rutinaEjercicio,item.Rutina_Ejercicio_ID));
quotaStep="personalizar rutina";const personalized=routine.exercises.map((item,index)=>({...item,Series:index===0?"4":"3",Observaciones:index===0?"ARU_TEST personalizado":"ARU_TEST original"}));result=await request(`/api/admin/rutinas/${routineId}`,{method:"PUT",headers:adminHeaders(adminCookie),body:JSON.stringify({session:{Alumno_ID:alumnoId,Dia_Entrenamiento_Semana:"Día 1",Fecha:"2026-08-16",Titulo:`ARU_TEST_RUTINA_${suffix}`,Notas_Generales:"ARU_TEST clon personalizado"},exercises:personalized})});assert.equal(result.response.status,200);
quotaStep="verificar independencia";const original=await new GoogleSheetsPlantillaEjercicioRepository().findBySesion(templateId);assert.equal(original[0]?.Series,"3");assert.equal(original[0]?.Observaciones,"ARU_TEST original");
// Separa las dos mitades del escenario para respetar la cuota por minuto sin reintentos automáticos.
await new Promise(resolve=>setTimeout(resolve,30_000));
quotaStep="login alumno";const studentCookie=await webSession(studentEmail,studentPassword);result=await request("/entrenamientos",{headers:{cookie:studentCookie}});assert.equal(result.response.status,200);assert.match(result.body,new RegExp(`ARU_TEST_RUTINA_${suffix}`));result=await request(`/entrenamientos/${routineId}`,{headers:{cookie:studentCookie}});assert.equal(result.response.status,200);assert.match(result.body,/Entrada en calor/);assert.match(result.body,/4/);assert.match(result.body,/example.com\/aru-test-1/);
const itemId=routine.exercises[0].Rutina_Ejercicio_ID;quotaStep="registrar progreso";result=await request("/api/alumno/progresos",{method:"POST",headers:adminHeaders(studentCookie),body:JSON.stringify({Rutina_Ejercicio_ID:itemId,Meta_Peso:25,Meta_Repeticiones:null,Meta_Tiempo:null})});assert.equal(result.response.status,201);const progressId=track(SHEET_NAMES.registroProgreso,result.json<{record:{Registro_ID:string}}>().record.Registro_ID);result=await request(`/entrenamientos/${routineId}`,{headers:{cookie:studentCookie}});assert.match(result.body,/25 kg/);result=await request(`/entrenamientos/${routineId}/ejercicios/${itemId}/historial`,{headers:{cookie:studentCookie}});assert.equal(result.response.status,200);assert.match(result.body,/25 kg/);
quotaStep="editar progreso";result=await request(`/api/alumno/progresos/${progressId}`,{method:"PUT",headers:adminHeaders(studentCookie),body:JSON.stringify({Meta_Peso:30,Meta_Repeticiones:8,Meta_Tiempo:null})});assert.equal(result.response.status,200);result=await request(`/entrenamientos/${routineId}/ejercicios/${itemId}/historial`,{headers:{cookie:studentCookie}});assert.match(result.body,/30 kg/);
quotaStep="completar entrenamiento";result=await request(`/api/alumno/entrenamientos/${routineId}/estado`,{method:"PATCH",headers:adminHeaders(studentCookie),body:JSON.stringify({completed:true})});assert.equal(result.response.status,200);result=await request("/api/auth/logout",{method:"POST",headers:{cookie:studentCookie,origin:baseUrl}});assert.equal(result.response.status,204);
quotaStep="revisión administrativa";const adminAgain=await webSession(adminEmail,adminPassword);result=await request(`/admin/alumnos/${alumnoId}`,{headers:{cookie:adminAgain}});assert.equal(result.response.status,200);assert.match(result.body,/30 kg/);assert.match(result.body,/12\.345/);result=await request(`/admin/rutinas?alumnoId=${alumnoId}`,{headers:{cookie:adminAgain}});assert.equal(result.response.status,200);assert.match(result.body,/Completado/);
quotaStep="deshabilitar alumno";result=await request(`/api/admin/alumnos/${alumnoId}/acceso`,{method:"PATCH",headers:adminHeaders(adminAgain),body:JSON.stringify({Activo:false})});assert.equal(result.response.status,200);result=await request(`/api/alumno/entrenamientos/${routineId}/estado`,{method:"PATCH",headers:adminHeaders(studentCookie),body:JSON.stringify({completed:true})});assert.ok([401,403].includes(result.response.status));quotaStep="rehabilitar alumno";result=await request(`/api/admin/alumnos/${alumnoId}/acceso`,{method:"PATCH",headers:adminHeaders(adminAgain),body:JSON.stringify({Activo:true})});assert.equal(result.response.status,200);await new Promise(resolve=>setTimeout(resolve,1100));const restoredCookie=await webSession(studentEmail,studentPassword);result=await request("/entrenamientos",{headers:{cookie:restoredCookie}});assert.equal(result.response.status,200);
});});
