import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { after, describe, it } from "node:test";
import { google } from "googleapis";
import { getFirebaseAdminAuth } from "@/infrastructure/firebase/admin";
import { GoogleSheetsAlumnoRepository, GoogleSheetsUsuarioRepository } from "@/infrastructure/sheets/repositories";
import { SHEET_NAMES } from "@/infrastructure/sheets/sheet-names";

const baseUrl=process.env.ARU_TEST_BASE_URL,spreadsheetId=process.env.GOOGLE_SHEETS_SPREADSHEET_ID,apiKey=process.env.NEXT_PUBLIC_FIREBASE_API_KEY;
const alumnoId=randomUUID(),adminUserId=randomUUID(),studentUserId=randomUUID(),firebaseUids:string[]=[];
async function cleanup(){for(const uid of firebaseUids)await getFirebaseAdminAuth().deleteUser(uid).catch(()=>undefined);if(!spreadsheetId)return;const api=google.sheets({version:"v4",auth:new google.auth.GoogleAuth({scopes:["https://www.googleapis.com/auth/spreadsheets"]})});const specs=[[SHEET_NAMES.usuarios,[adminUserId,studentUserId],"F"],[SHEET_NAMES.alumnos,[alumnoId],"K"]]as const;const response=await api.spreadsheets.values.batchGet({spreadsheetId,ranges:specs.map(([sheet])=>`'${sheet}'!A2:A`)});const ranges:string[]=[];specs.forEach(([sheet,ids,end],index)=>(response.data.valueRanges?.[index]?.values??[]).forEach((row,rowIndex)=>{if(ids.includes(String(row[0]??"")as never))ranges.push(`'${sheet}'!A${rowIndex+2}:${end}${rowIndex+2}`);}));if(ranges.length)await api.spreadsheets.values.batchClear({spreadsheetId,requestBody:{ranges}});}
after(cleanup);
async function login(email:string,password:string){const response=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${encodeURIComponent(apiKey!)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password,returnSecureToken:true})});assert.equal(response.status,200);return response.json()as Promise<{idToken:string}>;}
async function session(idToken:string){const response=await fetch(`${baseUrl}/api/auth/session`,{method:"POST",headers:{origin:baseUrl!,"content-type":"application/json"},body:JSON.stringify({idToken})});const body=await response.text();if(response.status===429||/quota|RESOURCE_EXHAUSTED/i.test(body))throw new Error("GOOGLE_SHEETS_QUOTA_AT:crear sesión");assert.equal(response.status,200,body);const cookie=response.headers.getSetCookie()[0]?.split(";",1)[0];assert.ok(cookie);return cookie;}
async function access(alumno:string,cookie:string,Activo:boolean){const response=await fetch(`${baseUrl}/api/admin/alumnos/${alumno}/acceso`,{method:"PATCH",headers:{cookie,origin:baseUrl!,"content-type":"application/json"},body:JSON.stringify({Activo})});const body=await response.text();if(response.status===429||/quota|RESOURCE_EXHAUSTED/i.test(body))throw new Error(`GOOGLE_SHEETS_QUOTA_AT:${Activo?"rehabilitar":"deshabilitar"}`);assert.equal(response.status,200,body);}

describe("focused user rehabilitation",()=>{it("requires a fresh Firebase login and creates a new session without timing delays",{timeout:60_000},async()=>{assert.ok(baseUrl);assert.ok(spreadsheetId);assert.ok(apiKey);const suffix=`${Date.now()}_${randomUUID().slice(0,8)}`,adminEmail=`aru_test_rehab_admin_${suffix}@example.com`,studentEmail=`aru_test_rehab_alumno_${suffix}@example.com`,adminPassword=`Aru!${randomBytes(24).toString("base64url")}`,studentPassword=`Aru!${randomBytes(24).toString("base64url")}`,firebase=getFirebaseAdminAuth(),users=new GoogleSheetsUsuarioRepository(),alumnos=new GoogleSheetsAlumnoRepository();
await alumnos.create({Alumno_ID:alumnoId,Documento:`ARU_TEST_REHAB_${suffix}`,Nombre:"ARU_TEST",Apellido:"REHABILITATION",Fecha_Nacimiento:"1990-01-01",Celular:"000",Mail:studentEmail,Fecha_Alta:"2026-08-15",Objetivo:"ARU_TEST",Dolencia:"",Observaciones:""});const adminFirebase=await firebase.createUser({email:adminEmail,password:adminPassword}),studentFirebase=await firebase.createUser({email:studentEmail,password:studentPassword});firebaseUids.push(adminFirebase.uid,studentFirebase.uid);await users.create({Usuario_ID:adminUserId,Alumno_ID:null,Email:adminEmail,Rol:"ADMIN",Activo:true,UID_Auth:adminFirebase.uid});await users.create({Usuario_ID:studentUserId,Alumno_ID:alumnoId,Email:studentEmail,Rol:"ALUMNO",Activo:true,UID_Auth:studentFirebase.uid});
const adminCookie=await session((await login(adminEmail,adminPassword)).idToken),firstToken=(await login(studentEmail,studentPassword)).idToken,oldCookie=await session(firstToken);let response=await fetch(`${baseUrl}/entrenamientos`,{headers:{cookie:oldCookie},redirect:"manual"});assert.equal(response.status,200);
await access(alumnoId,adminCookie,false);response=await fetch(`${baseUrl}/entrenamientos`,{headers:{cookie:oldCookie},redirect:"manual"});assert.ok([302,303,307,308,401,403].includes(response.status));
await access(alumnoId,adminCookie,true);response=await fetch(`${baseUrl}/entrenamientos`,{headers:{cookie:oldCookie},redirect:"manual"});assert.ok([302,303,307,308,401,403].includes(response.status));const secondToken=(await login(studentEmail,studentPassword)).idToken;assert.notEqual(secondToken,firstToken);const newCookie=await session(secondToken);assert.notEqual(newCookie,oldCookie);response=await fetch(`${baseUrl}/entrenamientos`,{headers:{cookie:newCookie},redirect:"manual"});assert.equal(response.status,200);response=await fetch(`${baseUrl}/api/auth/logout`,{method:"POST",headers:{cookie:newCookie,origin:baseUrl!}});assert.equal(response.status,204);
});});
