"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import type { RegistroProgreso } from "@/modules/progresos/domain/registro-progreso";
import { Button } from "@/components/ui/button";

const parse = (value: FormDataEntryValue | null) => String(value ?? "").trim() === "" ? null : Number(value);

export function ProgressForm({ endpoint, method = "POST", initial, rutinaEjercicioId }: { endpoint: string; method?: "POST" | "PUT"; initial?: RegistroProgreso; rutinaEjercicioId?: string }) {
  const router = useRouter(); const [saving,setSaving]=useState(false),[error,setError]=useState(""),[open,setOpen]=useState(Boolean(initial)),[saved,setSaved]=useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data=new FormData(event.currentTarget); const metrics={Meta_Peso:parse(data.get("peso")),Meta_Repeticiones:parse(data.get("repeticiones")),Meta_Tiempo:parse(data.get("tiempo"))}; if(Object.values(metrics).every(value=>value===null)){setError("Ingresá al menos una métrica para guardar.");return} setSaving(true);setError("");try{const body=rutinaEjercicioId?{...metrics,Rutina_Ejercicio_ID:rutinaEjercicioId}:metrics;const response=await fetch(endpoint,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw new Error();if(!initial)event.currentTarget.reset();setSaved(true);if(!initial)setOpen(false);router.refresh()}catch{setError("No pudimos guardar el progreso. Revisá los valores.")}finally{setSaving(false)}}
  const form=<form className="space-y-5" onSubmit={submit}><div><h3 className="text-xl font-extrabold">{initial?"Corregir marca":"Registrar progreso"}</h3><p className="mt-1 text-sm text-slate-600">Completá sólo las métricas que quieras guardar.</p></div><div className="grid gap-3 sm:grid-cols-3"><MetricInput initial={initial?.Meta_Peso} label="Peso" name="peso" suffix="kg" step="any"/><MetricInput initial={initial?.Meta_Repeticiones} label="Repeticiones" name="repeticiones" suffix="reps" step="1"/><MetricInput initial={initial?.Meta_Tiempo} label="Tiempo" name="tiempo" suffix="s" step="any"/></div>{error?<p className="rounded-xl bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</p>:null}<div className="flex flex-wrap justify-end gap-2">{!initial?<Button className="border border-violet-700 bg-white text-violet-700 shadow-none hover:bg-violet-50" onClick={()=>setOpen(false)}>Cancelar</Button>:null}<Button disabled={saving} type="submit">{saving?"Guardando…":initial?"Guardar corrección":"Guardar progreso"}</Button></div></form>;
  if(initial)return form;
  return <><Button className="w-full sm:w-auto" onClick={()=>{setOpen(true);setSaved(false)}}>Registrar progreso</Button>{saved?<p className="mt-2 text-sm font-semibold text-emerald-700" role="status">✓ Progreso guardado</p>:null}{open?<div aria-label="Registrar progreso" aria-modal="true" className="fixed inset-0 z-50 flex items-end bg-slate-950/35 p-0 sm:items-center sm:justify-center sm:p-5" role="dialog"><div className="max-h-[90vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:max-w-lg sm:rounded-3xl sm:p-7">{form}</div></div>:null}</>;
}

function MetricInput({label,name,step,suffix,initial}:{label:string;name:string;step:string;suffix:string;initial?:number|null}) { return <label className="text-sm font-bold text-slate-700">{label}<span className="mt-1 flex min-h-12 items-center rounded-xl border border-slate-300 bg-white px-3 focus-within:border-violet-600 focus-within:ring-4 focus-within:ring-violet-100"><input className="min-w-0 flex-1 border-0 bg-transparent py-2 outline-none" defaultValue={initial??""} inputMode="decimal" min="0" name={name} step={step} type="number"/><span className="text-sm text-slate-500">{suffix}</span></span></label>;}
