"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import type { RegistroProgreso } from "@/modules/progresos/domain/registro-progreso";
const parse = (value: FormDataEntryValue | null) => String(value ?? "").trim() === "" ? null : Number(value);
export function ProgressForm({ endpoint, method = "POST", initial, rutinaEjercicioId }: { endpoint: string; method?: "POST" | "PUT"; initial?: RegistroProgreso; rutinaEjercicioId?: string }) {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const metrics = { Meta_Peso: parse(data.get("peso")), Meta_Repeticiones: parse(data.get("repeticiones")), Meta_Tiempo: parse(data.get("tiempo")) }; if (Object.values(metrics).every((value) => value === null)) { setError("Ingresá al menos una métrica para guardar."); return; } setSaving(true); setError(""); try { const body = rutinaEjercicioId ? { ...metrics, Rutina_Ejercicio_ID: rutinaEjercicioId } : metrics; const response = await fetch(endpoint, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(); if (!initial) event.currentTarget.reset(); router.refresh(); } catch { setError("No pudimos guardar el progreso. Revisá los valores."); } finally { setSaving(false); } }
  return <form className="space-y-3" onSubmit={submit}><div className="grid grid-cols-3 gap-2 sm:gap-3"><MetricInput initial={initial?.Meta_Peso} label="Peso (kg)" name="peso" step="any"/><MetricInput initial={initial?.Meta_Repeticiones} label="Repeticiones" name="repeticiones" step="1"/><MetricInput initial={initial?.Meta_Tiempo} label="Tiempo (s)" name="tiempo" step="any"/></div>{error ? <p className="text-sm text-red-700" role="alert">{error}</p> : null}<button className="min-h-10 rounded-lg bg-violet-700 px-4 text-sm font-bold text-white disabled:opacity-60" disabled={saving}>{saving ? "Guardando…" : initial ? "Guardar corrección" : "Guardar progreso"}</button></form>;
}
function MetricInput({ label, name, step, initial }: { label: string; name: string; step: string; initial?: number | null }) { return <label className="text-xs font-bold text-slate-600">{label}<input className="mt-1 min-h-10 w-full min-w-0 rounded-lg border border-slate-300 px-2 font-normal" defaultValue={initial ?? ""} min="0" name={name} step={step} type="number"/></label>; }
