import Link from "next/link";
import { AlumnoHeader } from "@/components/alumno/alumno-header";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { StatusBadge } from "@/components/ui/status-badge";
import { getAuthenticatedAlumnoId } from "@/modules/auth/infrastructure/current-user";
import { getEntrenamientoAlumnoService } from "@/modules/entrenamientos/infrastructure/entrenamiento-alumno-service-factory";

export default async function TodosPage({searchParams}:{searchParams:Promise<{vista?:string}>}) { const alumnoId=await getAuthenticatedAlumnoId();const{vista="todos"}=await searchParams;const data=await getEntrenamientoAlumnoService().list(alumnoId);const all=[...data.upcoming,...data.previous];const unique=[...new Map(all.map(entry=>[entry.session.Rutina_Sesion_ID,entry])).values()];const rows=unique.filter(({session})=>vista==="proximos"?!session.Entrenamiento_Completado&&data.upcoming.some(x=>x.session.Rutina_Sesion_ID===session.Rutina_Sesion_ID):vista==="anteriores"?!session.Entrenamiento_Completado&&data.previous.some(x=>x.session.Rutina_Sesion_ID===session.Rutina_Sesion_ID):vista==="completados"?session.Entrenamiento_Completado:true);return <><AlumnoHeader/><main className="mx-auto max-w-3xl space-y-6 px-4 py-6 sm:px-6 sm:py-10"><header><p className="eyebrow">Mis entrenamientos</p><h1 className="text-3xl font-extrabold">Todos los entrenamientos</h1></header><nav className="flex flex-wrap gap-2">{[["todos","Todos"],["proximos","Próximos"],["anteriores","Anteriores"],["completados","Completados"]].map(([key,label])=><Link className={`rounded-full px-4 py-2 text-sm font-bold ${vista===key?"bg-violet-700 text-white":"border border-slate-300 bg-white"}`} href={`/entrenamientos/todos?vista=${key}`} key={key}>{label}</Link>)}</nav>{rows.length?<div className="grid gap-3 sm:grid-cols-2">{rows.map(({session,state})=><Link href={`/entrenamientos/${session.Rutina_Sesion_ID}`} key={session.Rutina_Sesion_ID}><Card className="h-full space-y-2"><div className="flex justify-between gap-3"><h2 className="font-extrabold">{session.Titulo}</h2><StatusBadge label={session.Entrenamiento_Completado?"Completado":state==="pendiente"?"Anterior pendiente":"Próximo"} tone={session.Entrenamiento_Completado?"success":"warning"}/></div><p className="text-sm text-slate-600">{session.Dia_Entrenamiento_Semana} · {new Date(`${session.Fecha}T00:00:00`).toLocaleDateString("es-AR")}</p></Card></Link>)}</div>:<EmptyState icon="○" title="Sin entrenamientos" description="No hay entrenamientos en esta categoría."/>}</main></> }
