import Link from "next/link";
import { notFound } from "next/navigation";
import { Card } from "@/components/ui/card";
import { EjercicioForm } from "@/components/admin/ejercicio-form";
import { ExerciseBadge } from "@/components/admin/exercise-badge";
import { ExerciseStateButton } from "@/components/admin/exercise-state-button";
import { EjercicioAdminError } from "@/modules/ejercicios/application/errors";
import { requireAdmin } from "@/modules/auth/infrastructure/current-user";
import { getEjercicioAdminService } from "@/modules/ejercicios/infrastructure/ejercicio-admin-service-factory";
export default async function EjercicioPage({params}:{params:Promise<{id:string}>}){await requireAdmin();const{id}=await params;let item;try{item=await getEjercicioAdminService().get(id);}catch(error){if(error instanceof EjercicioAdminError)notFound();throw error;}return <main className="mx-auto max-w-4xl space-y-6 px-5 py-8"><Link className="text-sm font-semibold text-violet-700" href="/admin/ejercicios">← Volver al catálogo</Link><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-violet-700">Detalle del ejercicio</p><h1 className="text-3xl font-black">{item.Ejercicio}</h1><p className="text-sm text-slate-500">ID: {item.Catalogo_ID}</p></div><ExerciseBadge active={item.Activo}/></div><Card className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex flex-wrap gap-3">{item.Video?<a className="rounded-lg border border-violet-700 px-4 py-2 font-semibold text-violet-700" href={item.Video} rel="noopener noreferrer" target="_blank">Abrir video</a>:null}{item.Video_Adicional?<a className="rounded-lg border border-violet-700 px-4 py-2 font-semibold text-violet-700" href={item.Video_Adicional} rel="noopener noreferrer" target="_blank">Abrir video adicional</a>:null}{!item.Video&&!item.Video_Adicional?<p className="text-sm text-slate-600">Este ejercicio no tiene videos asociados.</p>:null}</div><ExerciseStateButton active={item.Activo} id={item.Catalogo_ID}/></Card><Card><h2 className="mb-5 text-xl font-bold">Información</h2><EjercicioForm ejercicio={item}/></Card></main>;}
