import Link from "next/link";
import { notFound } from "next/navigation";
import { AlumnoHeader } from "@/components/alumno/alumno-header";
import { CompletionButton } from "@/components/alumno/completion-button";
import { ProgressForm } from "@/components/progreso/progress-form";
import { ProgressMetrics } from "@/components/progreso/progress-metrics";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { StatusBadge } from "@/components/ui/status-badge";
import { getAuthenticatedAlumnoId } from "@/modules/auth/infrastructure/current-user";
import { EntrenamientoAlumnoError } from "@/modules/entrenamientos/application/errors";
import { getEntrenamientoAlumnoService } from "@/modules/entrenamientos/infrastructure/entrenamiento-alumno-service-factory";

const Value=({label,value}:{label:string;value:string})=>value?<div className="rounded-xl bg-slate-50 p-3"><dt className="text-[.68rem] font-bold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 font-bold text-slate-900">{value}</dd></div>:null;

export default async function EntrenamientoDetallePage({params}:{params:Promise<{rutinaId:string}>}) {
  const alumnoId=await getAuthenticatedAlumnoId(); const{rutinaId}=await params;let detail;try{detail=await getEntrenamientoAlumnoService().detail(alumnoId,rutinaId)}catch(error){if(error instanceof EntrenamientoAlumnoError)notFound();throw error}const{session,blocks}=detail;
  return <><AlumnoHeader/><main className="mx-auto max-w-3xl space-y-8 px-4 py-6 pb-16 sm:px-6 sm:py-10"><Link className="brand-link inline-flex min-h-11 items-center font-bold" href="/entrenamientos">← Mis entrenamientos</Link><header className="space-y-3"><div className="flex flex-wrap items-center gap-3"><p className="eyebrow">{session.Dia_Entrenamiento_Semana}</p><StatusBadge label={session.Entrenamiento_Completado?"Completado":"Pendiente"} tone={session.Entrenamiento_Completado?"success":"warning"}/></div><h1 className="text-3xl font-extrabold sm:text-4xl">{session.Titulo}</h1><p className="text-slate-600">{new Date(`${session.Fecha}T00:00:00`).toLocaleDateString("es-AR",{weekday:"long",day:"numeric",month:"long"})}</p>{session.Notas_Generales?<p className="rounded-2xl border border-violet-100 bg-violet-50 p-4 text-slate-700">{session.Notas_Generales}</p>:null}</header>
    {!blocks.length?<EmptyState icon="○" title="Esta rutina todavía no tiene ejercicios" description="Consultá con tu entrenadora para completar la planificación."/>:null}
    {blocks.map(block=><section className="space-y-3" key={block.order}><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-full bg-violet-700 text-sm font-extrabold text-white">{block.order}</span><h2 className="text-xl font-extrabold">{block.name}</h2></div>{block.exercises.map(({item,catalog,latest},index)=><Card className="space-y-5 p-4 sm:p-5" key={item.Rutina_Ejercicio_ID}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-violet-700">Ejercicio {index+1}</p><h3 className="mt-1 text-xl font-extrabold">{catalog?.Ejercicio??"Ejercicio no disponible"}</h3><p className="text-sm text-slate-500">{catalog?.Tipo_de_Ejercicio}</p></div>{catalog&&!catalog.Activo?<StatusBadge label="Archivado"/>:null}</div><dl className="grid grid-cols-2 gap-2 sm:grid-cols-3"><Value label="Series" value={item.Series}/><Value label="Reps / tiempo" value={item.Reps_Tiempo}/><Value label="Carga" value={item.Carga}/><Value label="RIR" value={item.RIR}/><Value label="Descanso" value={item.Descanso}/></dl>
      {(item.Instrumento_Alternativo||item.Observaciones||catalog?.Aclaraciones||catalog?.Video||catalog?.Video_Adicional)?<details className="rounded-xl border border-slate-200 bg-white"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between px-4 font-bold text-violet-700">Ver ejercicio <span aria-hidden>＋</span></summary><div className="space-y-3 border-t border-slate-100 p-4 text-sm">{item.Instrumento_Alternativo?<p><strong>Alternativa:</strong> {item.Instrumento_Alternativo}</p>:null}{item.Observaciones?<p><strong>Indicaciones:</strong> {item.Observaciones}</p>:null}{catalog?.Aclaraciones?<p><strong>Aclaraciones:</strong> {catalog.Aclaraciones}</p>:null}<div className="flex flex-wrap gap-4">{catalog?.Video?<a className="brand-link font-bold" href={catalog.Video} rel="noopener noreferrer" target="_blank">Abrir en YouTube ↗</a>:null}{catalog?.Video_Adicional?<a className="brand-link font-bold" href={catalog.Video_Adicional} rel="noopener noreferrer" target="_blank">Video adicional ↗</a>:null}</div></div></details>:null}
      <section className="space-y-3 border-t border-violet-100 pt-4"><h4 className="font-extrabold">Mi progreso</h4>{latest?<p className="rounded-xl bg-violet-50 p-3 text-sm"><strong>Última marca:</strong> <ProgressMetrics record={latest}/> · {new Date(latest.Fecha_Registro).toLocaleDateString("es-AR")}</p>:<p className="text-sm text-slate-600">Todavía no registraste una marca para este ejercicio.</p>}<div className="flex flex-col gap-2 sm:flex-row sm:items-center"><ProgressForm endpoint="/api/alumno/progresos" rutinaEjercicioId={item.Rutina_Ejercicio_ID}/><Link className="brand-link inline-flex min-h-11 items-center justify-center text-sm font-bold" href={`/entrenamientos/${rutinaId}/ejercicios/${item.Rutina_Ejercicio_ID}/historial`}>Ver historial →</Link></div></section></Card>)}</section>)}
    <section className="space-y-3 border-t border-slate-200 pt-7"><h2 className="text-xl font-extrabold">¿Terminaste?</h2><p className="text-sm text-slate-600">Completar el entrenamiento es independiente de registrar progreso.</p><CompletionButton completed={session.Entrenamiento_Completado} rutinaId={session.Rutina_Sesion_ID}/></section>
  </main></>;
}
