import assert from "node:assert/strict";
import test from "node:test";
import { z } from "zod";
import type { Alumno } from "@/modules/alumnos/domain/alumno";
import type { AlumnoRepository } from "@/modules/alumnos/domain/repository";
import type { Cobro } from "@/modules/cobros/domain/cobro";
import type { CobroRepository } from "@/modules/cobros/domain/repository";
import { createCobroAdminService } from "@/modules/cobros/application/cobro-admin-service";
import { CobroAdminError } from "@/modules/cobros/application/errors";
const alumno:Alumno={Alumno_ID:"11111111-1111-4111-8111-111111111111",Documento:"ARU_TEST",Nombre:"Ana",Apellido:"Prueba",Fecha_Nacimiento:"1990-01-01",Celular:"",Mail:"test@example.invalid",Fecha_Alta:"2026-08-15",Objetivo:"",Dolencia:"",Observaciones:""};
class Alumnos implements AlumnoRepository{values=[alumno];findAll=async()=>this.values;findById=async(id:string)=>this.values.find(x=>x.Alumno_ID===id)??null;search=async()=>this.values;create=async()=>{};update=async()=>{};save=async()=>{};}
class Cobros implements CobroRepository{constructor(public values:Cobro[]=[]){ }findAll=async()=>this.values;findById=async(id:string)=>this.values.find(x=>x.Cobro_ID===id)??null;findByAlumno=async(id:string)=>this.values.filter(x=>x.Alumno_ID===id);create=async(x:Cobro)=>{this.values.push(x)};update=async(x:Cobro)=>{this.values=this.values.map(v=>v.Cobro_ID===x.Cobro_ID?x:v)};save=this.update;}
const pending={Alumno_ID:alumno.Alumno_ID,Mes_Abonado:"2026-08",Fecha_Pago:null,Importe:10000,Estado_Pago:"PENDIENTE" as const,Medio_Pago:"TRANSFERENCIA" as const};
test("creates paid and pending charges with server UUID",async()=>{const repo=new Cobros();const service=createCobroAdminService({cobros:repo,alumnos:new Alumnos()});const first=await service.create(pending);assert.match(first.Cobro_ID,/^[0-9a-f-]{36}$/);const paid=await service.create({...pending,Fecha_Pago:"2026-08-10",Importe:12000,Estado_Pago:"PAGADO",Medio_Pago:"EFECTIVO"});assert.equal(paid.Estado_Pago,"PAGADO");assert.equal(repo.values.length,2);});
test("rejects unknown students and paid charges without date",async()=>{const service=createCobroAdminService({cobros:new Cobros(),alumnos:new Alumnos()});await assert.rejects(()=>service.create({...pending,Alumno_ID:"22222222-2222-4222-8222-222222222222"}),(error:unknown)=>error instanceof CobroAdminError&&error.code==="ALUMNO_NOT_FOUND");await assert.rejects(()=>service.create({...pending,Estado_Pago:"PAGADO"}),(error:unknown)=>error instanceof z.ZodError);});
test("filters and calculates paid total and pending count",async()=>{const rows=[{...pending,Cobro_ID:"33333333-3333-4333-8333-333333333331"},{...pending,Cobro_ID:"33333333-3333-4333-8333-333333333332",Mes_Abonado:"2026-07",Fecha_Pago:"2026-07-05",Importe:15000,Estado_Pago:"PAGADO" as const}];const service=createCobroAdminService({cobros:new Cobros(rows),alumnos:new Alumnos()});const august=await service.list({search:"ana prueba",month:"2026-08",status:"PENDIENTE"});assert.equal(august.entries.length,1);assert.equal(august.summary.pendientes,1);assert.equal(august.summary.totalCobrado,0);const all=await service.list();assert.equal(all.summary.totalCobrado,15000);assert.equal(all.summary.registrados,2);});
test("edits fields while preserving Cobro_ID",async()=>{const original={...pending,Cobro_ID:"33333333-3333-4333-8333-333333333333"};const repo=new Cobros([original]);const service=createCobroAdminService({cobros:repo,alumnos:new Alumnos()});const edited=await service.update(original.Cobro_ID,{...pending,Fecha_Pago:"2026-08-15",Importe:20000,Estado_Pago:"PAGADO",Medio_Pago:"EFECTIVO"});assert.equal(edited.Cobro_ID,original.Cobro_ID);assert.equal(edited.Importe,20000);});
