import assert from "node:assert/strict";
import test from "node:test";
import type { Ejercicio } from "@/modules/ejercicios/domain/ejercicio";
import type { EjercicioRepository } from "@/modules/ejercicios/domain/repository";
import type { RutinaEjercicio, RutinaSesion } from "@/modules/rutinas/domain/rutina";
import type { RutinaEjercicioRepository, RutinaSesionRepository } from "@/modules/rutinas/domain/repository";
import { createEntrenamientoAlumnoService } from "@/modules/entrenamientos/application/entrenamiento-alumno-service";
import { EntrenamientoAlumnoError } from "@/modules/entrenamientos/application/errors";

const ownId = "11111111-1111-4111-8111-111111111111";
const otherId = "22222222-2222-4222-8222-222222222222";
const session = (id: string, alumnoId: string, date: string, completed = false): RutinaSesion => ({ Rutina_Sesion_ID: id, Alumno_ID: alumnoId, Dia_Entrenamiento_Semana: "Día 1", Fecha: date, Titulo: id, Notas_Generales: "", Plantilla_Sesion_Origen_ID: null, Entrenamiento_Completado: completed, Fecha_Completado: completed ? date : null });
class Sessions implements RutinaSesionRepository { constructor(public values: RutinaSesion[]) {} findAll = async () => this.values; findById = async (id: string) => this.values.find((x) => x.Rutina_Sesion_ID === id) ?? null; findByAlumno = async (id: string) => this.values.filter((x) => x.Alumno_ID === id).sort((a, b) => a.Fecha.localeCompare(b.Fecha)); create = async () => {}; update = async (value: RutinaSesion) => { this.values = this.values.map((x) => x.Rutina_Sesion_ID === value.Rutina_Sesion_ID ? value : x); }; save = this.update; markCompleted = async () => {}; removeCreated = async () => {}; }
class Items implements RutinaEjercicioRepository { constructor(public values: RutinaEjercicio[] = []) {} findAll = async () => this.values; findById = async () => null; findBySesion = async (id: string) => this.values.filter((x) => x.Rutina_Sesion_ID === id); create = async () => {}; update = async () => {}; save = async () => {}; replaceForSesion = async () => {}; }
class Catalog implements EjercicioRepository { constructor(public values: Ejercicio[] = []) {} findAll = async () => this.values; findById = async () => null; create = async () => {}; update = async () => {}; save = async () => {}; }
function makeService(sessions: Sessions, items = new Items(), catalog = new Catalog()) { return createEntrenamientoAlumnoService({ sessions, items, catalog, now: () => new Date("2026-08-15T15:00:00Z") }); }

test("classifies next, future, completed and overdue pending routines", async () => { const values = [session("33333333-3333-4333-8333-333333333331", ownId, "2026-08-10"), session("33333333-3333-4333-8333-333333333332", ownId, "2026-08-16"), session("33333333-3333-4333-8333-333333333333", ownId, "2026-08-20", true), session("33333333-3333-4333-8333-333333333334", otherId, "2026-08-15")]; const result = await makeService(new Sessions(values)).list(ownId); assert.equal(result.next?.Rutina_Sesion_ID, values[1].Rutina_Sesion_ID); assert.equal(result.upcoming.length, 2); assert.equal(result.previous[0].state, "pendiente"); assert.equal(result.upcoming[1].state, "completado"); });
test("rejects horizontal detail and completion access", async () => { const foreign = session("33333333-3333-4333-8333-333333333333", otherId, "2026-08-16"); const service = makeService(new Sessions([foreign])); await assert.rejects(() => service.detail(ownId, foreign.Rutina_Sesion_ID), (error: unknown) => error instanceof EntrenamientoAlumnoError && error.code === "RUTINA_FORBIDDEN"); await assert.rejects(() => service.setCompleted(ownId, foreign.Rutina_Sesion_ID, true), (error: unknown) => error instanceof EntrenamientoAlumnoError && error.code === "RUTINA_FORBIDDEN"); });
test("orders blocks/exercises, joins archived catalog and handles empty routines", async () => { const own = session("33333333-3333-4333-8333-333333333333", ownId, "2026-08-16"); const exercise = (id: string, block: number, order: number): RutinaEjercicio => ({ Rutina_Ejercicio_ID: id, Rutina_Sesion_ID: own.Rutina_Sesion_ID, Catalogo_ID: "LEGACY-1", Tipo_Bloque: `Bloque ${block}`, Orden_Bloque: block, Orden_Ejercicio: order, Instrumento_Alternativo: "Banda", Reps_Tiempo: "10", Series: "3", Carga: "5", Descanso: "30", RIR: "2", Observaciones: "Test" }); const archived: Ejercicio = { Catalogo_ID: "LEGACY-1", Tipo_de_Ejercicio: "Fuerza", Ejercicio: "ARU_TEST", Video: "https://example.com/1", Video_Adicional: "https://example.com/2", Aclaraciones: "Test", Activo: false }; const service = makeService(new Sessions([own]), new Items([exercise("44444444-4444-4444-8444-444444444442", 2, 2), exercise("44444444-4444-4444-8444-444444444441", 1, 3)]), new Catalog([archived])); const detail = await service.detail(ownId, own.Rutina_Sesion_ID); assert.deepEqual(detail.blocks.map((block) => block.order), [1, 2]); assert.equal(detail.blocks[0].exercises[0].catalog?.Activo, false); assert.deepEqual((await makeService(new Sessions([own])).detail(ownId, own.Rutina_Sesion_ID)).blocks, []); });
test("sets and clears completion date on the backend clock", async () => { const own = session("33333333-3333-4333-8333-333333333333", ownId, "2026-08-16"); const sessions = new Sessions([own]); const service = makeService(sessions); const completed = await service.setCompleted(ownId, own.Rutina_Sesion_ID, true); assert.equal(completed.Fecha_Completado, "2026-08-15"); const pending = await service.setCompleted(ownId, own.Rutina_Sesion_ID, false); assert.equal(pending.Fecha_Completado, null); });
