import assert from "node:assert/strict";
import test from "node:test";
import { z } from "zod";
import type { Ejercicio } from "@/modules/ejercicios/domain/ejercicio";
import type { EjercicioRepository } from "@/modules/ejercicios/domain/repository";
import type { RegistroProgreso } from "@/modules/progresos/domain/registro-progreso";
import type { RegistroProgresoRepository } from "@/modules/progresos/domain/repository";
import { createProgresoService } from "@/modules/progresos/application/progreso-service";
import { ProgresoError } from "@/modules/progresos/application/errors";
import type { RutinaEjercicio, RutinaSesion } from "@/modules/rutinas/domain/rutina";
import type { RutinaEjercicioRepository, RutinaSesionRepository } from "@/modules/rutinas/domain/repository";
const alumno = "11111111-1111-4111-8111-111111111111", other = "22222222-2222-4222-8222-222222222222", routine = "33333333-3333-4333-8333-333333333333", itemId = "44444444-4444-4444-8444-444444444444", catalogId = "55555555-5555-4555-8555-555555555555";
const session: RutinaSesion = { Rutina_Sesion_ID: routine, Alumno_ID: alumno, Dia_Entrenamiento_Semana: "Día 1", Fecha: "2026-08-15", Titulo: "Test", Notas_Generales: "", Plantilla_Sesion_Origen_ID: null, Entrenamiento_Completado: false, Fecha_Completado: null };
const item: RutinaEjercicio = { Rutina_Ejercicio_ID: itemId, Rutina_Sesion_ID: routine, Catalogo_ID: catalogId, Tipo_Bloque: "Test", Orden_Bloque: 1, Orden_Ejercicio: 1, Instrumento_Alternativo: "", Reps_Tiempo: "", Series: "", Carga: "", Descanso: "", RIR: "", Observaciones: "" };
class Progress implements RegistroProgresoRepository { constructor(public values: RegistroProgreso[] = []) {} findAll=async()=>this.values; findById=async(id:string)=>this.values.find(x=>x.Registro_ID===id)??null; findHistory=async(a:string,c:string)=>this.values.filter(x=>x.Alumno_ID===a&&x.Catalogo_ID===c).sort((x,y)=>y.Fecha_Registro.localeCompare(x.Fecha_Registro)); findLatest=async(a:string,c:string)=>(await this.findHistory(a,c))[0]??null; create=async(x:RegistroProgreso)=>{this.values.push(x)}; update=async(x:RegistroProgreso)=>{this.values=this.values.map(v=>v.Registro_ID===x.Registro_ID?x:v)}; save=this.update; }
class Items implements RutinaEjercicioRepository { findAll=async()=>[item]; findById=async(id:string)=>id===itemId?item:null; findBySesion=async()=>[item]; create=async()=>{};update=async()=>{};save=async()=>{};replaceForSesion=async()=>{}; }
class Sessions implements RutinaSesionRepository { findAll=async()=>[session];findById=async(id:string)=>id===routine?session:null;findByAlumno=async()=>[session];create=async()=>{};update=async()=>{};save=async()=>{};markCompleted=async()=>{};removeCreated=async()=>{}; }
class Catalog implements EjercicioRepository { values:Ejercicio[]=[{Catalogo_ID:catalogId,Tipo_de_Ejercicio:"Fuerza",Ejercicio:"Peso muerto",Video:"",Video_Adicional:"",Aclaraciones:"",Activo:true}];findAll=async()=>this.values;findById=async(id:string)=>this.values.find(x=>x.Catalogo_ID===id)??null;create=async()=>{};update=async()=>{};save=async()=>{}; }
const setup=()=>{const progress=new Progress();return{progress,service:createProgresoService({progress,items:new Items(),sessions:new Sessions(),catalog:new Catalog(),now:()=>new Date("2026-08-15T12:00:00.000Z")})}};
test("creates every metric combination and preserves explicit zero",async()=>{const{service,progress}=setup();for(const metrics of [{Meta_Peso:70,Meta_Repeticiones:null,Meta_Tiempo:null},{Meta_Peso:null,Meta_Repeticiones:12,Meta_Tiempo:null},{Meta_Peso:null,Meta_Repeticiones:null,Meta_Tiempo:60},{Meta_Peso:10,Meta_Repeticiones:50,Meta_Tiempo:null},{Meta_Peso:10,Meta_Repeticiones:50,Meta_Tiempo:60},{Meta_Peso:0,Meta_Repeticiones:null,Meta_Tiempo:null}])await service.create(alumno,itemId,metrics);assert.equal(progress.values.length,6);assert.equal(progress.values.at(-1)?.Meta_Peso,0);assert.equal(progress.values[0].Alumno_ID,alumno);assert.equal(progress.values[0].Catalogo_ID,catalogId);});
test("rejects an empty row instead of creating it",async()=>{const{service,progress}=setup();await assert.rejects(()=>service.create(alumno,itemId,{Meta_Peso:null,Meta_Repeticiones:null,Meta_Tiempo:null}),(error:unknown)=>error instanceof z.ZodError);assert.equal(progress.values.length,0);});
test("rejects foreign creation and editing",async()=>{const{service,progress}=setup();await assert.rejects(()=>service.create(other,itemId,{Meta_Peso:1,Meta_Repeticiones:null,Meta_Tiempo:null}),(error:unknown)=>error instanceof ProgresoError&&error.code==="FORBIDDEN");const own=await service.create(alumno,itemId,{Meta_Peso:1,Meta_Repeticiones:null,Meta_Tiempo:null});await assert.rejects(()=>service.updateOwn(other,own.Registro_ID,{Meta_Peso:2,Meta_Repeticiones:null,Meta_Tiempo:null}),(error:unknown)=>error instanceof ProgresoError&&error.code==="FORBIDDEN");assert.equal(progress.values[0].Meta_Peso,1);});
test("shares chronological history by catalog and preserves ownership on edits",async()=>{const{service,progress}=setup();const older=await service.create(alumno,itemId,{Meta_Peso:10,Meta_Repeticiones:null,Meta_Tiempo:null});progress.values.push({...older,Registro_ID:"66666666-6666-4666-8666-666666666666",Rutina_Ejercicio_ID:"77777777-7777-4777-8777-777777777777",Fecha_Registro:"2026-08-16T12:00:00.000Z",Meta_Peso:20});const history=await service.historyForItem(alumno,itemId);assert.equal(history[0].Meta_Peso,20);const updated=await service.updateAdmin(older.Registro_ID,{Meta_Peso:null,Meta_Repeticiones:8,Meta_Tiempo:null});assert.equal(updated.Alumno_ID,alumno);assert.equal(updated.Catalogo_ID,catalogId);assert.equal(updated.Rutina_Ejercicio_ID,itemId);assert.equal(updated.Fecha_Registro,older.Fecha_Registro);});
test("joins the exercise name and only lists the authenticated student's progress",async()=>{const{service,progress}=setup();const own=await service.create(alumno,itemId,{Meta_Peso:40,Meta_Repeticiones:null,Meta_Tiempo:null});progress.values.push({...own,Registro_ID:"99999999-9999-4999-8999-999999999999",Alumno_ID:other});const detail=await service.historyDetailForItem(alumno,itemId);assert.equal(detail.catalog?.Ejercicio,"Peso muerto");const rows=await service.listForAlumno(alumno);assert.equal(rows.length,1);assert.equal(rows[0].sessionId,routine);assert.equal(rows[0].record.Alumno_ID,alumno);});
