import Link from "next/link";
import { AlumnoHeader } from "@/components/alumno/alumno-header";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { StatusBadge } from "@/components/ui/status-badge";
import { ProgressMetrics } from "@/components/progreso/progress-metrics";
import { getAuthenticatedAlumnoId } from "@/modules/auth/infrastructure/current-user";
import { getEntrenamientoAlumnoService } from "@/modules/entrenamientos/infrastructure/entrenamiento-alumno-service-factory";
import { getProgresoService } from "@/modules/progresos/infrastructure/progreso-service-factory";
import type { RutinaSesion } from "@/modules/rutinas/domain/rutina";

function RoutineCard({session,label,featured=false}:{session:RutinaSesion;label:string;featured?:boolean}) { return <Link href={`/entrenamientos/${session.Rutina_Sesion_ID}`}><Card className={`group h-full transition hover:-translate-y-0.5 hover:border-violet-300 hover:shadow-md ${featured?"border-violet-200 bg-gradient-to-br from-white to-violet-50 p-6 sm:p-7":""}`}><div className="flex items-start justify-between gap-3"><div><p className="eyebrow">{session.Dia_Entrenamiento_Semana}</p><h3 className={`${featured?"mt-2 text-2xl":"text-lg"} font-extrabold`}>{session.Titulo}</h3></div><StatusBadge label={label} tone={session.Entrenamiento_Completado?"success":"warning"}/></div><p className="mt-4 text-sm text-slate-600">{new Date(`${session.Fecha}T00:00:00`).toLocaleDateString("es-AR",{weekday:"long",day:"numeric",month:"long"})}</p><span className="mt-5 inline-flex min-h-11 items-center font-bold text-violet-700">Ver entrenamiento →</span></Card></Link> }

export default async function EntrenamientosPage(){const alumnoId=await getAuthenticatedAlumnoId();const[data,progress]=await Promise.all([getEntrenamientoAlumnoService().list(alumnoId),getProgresoService().listForAlumno(alumnoId)]);const total=data.upcoming.length+data.previous.length;const otherUpcoming=data.upcoming.filter(({session})=>session.Rutina_Sesion_ID!==data.next?.Rutina_Sesion_ID).slice(0,3);return <><AlumnoHeader/><main className="mx-auto max-w-3xl space-y-9 px-4 py-6 pb-16 sm:px-6 sm:py-10"><header><p className="eyebrow">Tu espacio</p><h1 className="text-3xl font-extrabold sm:text-4xl">¿Qué entrenamos hoy?</h1><p className="mt-2 text-slate-600">Tus sesiones y marcas recientes, siempre a mano.</p></header>{!total?<EmptyState icon="🏋" title="Todavía no tenés entrenamientos" description="Cuando tu entrenadora asigne una rutina, va a aparecer acá."/>:null}{data.next?<section className="space-y-3"><h2 className="text-xl font-bold">Próximo entrenamiento</h2><RoutineCard featured label="Próximo" session={data.next}/></section>:null}{otherUpcoming.length?<section className="space-y-3"><h2 className="text-xl font-bold">Después viene</h2><div className="grid gap-3 sm:grid-cols-2">{otherUpcoming.map(({session,state})=><RoutineCard key={session.Rutina_Sesion_ID} label={state==="completado"?"Completado":"Próximo"} session={session}/>)}</div></section>:null}{total?<Link className="brand-link inline-flex min-h-11 items-center font-bold" href="/entrenamientos/todos">Ver todos mis entrenamientos →</Link>:null}<section className="space-y-3"><div><h2 className="text-xl font-bold">Tu progreso</h2><p className="text-sm text-slate-600">Tus últimos registros, no importa en qué rutina los cargaste.</p></div>{progress.length?<div className="grid gap-3 sm:grid-cols-3">{progress.slice(0,3).map(({record,catalog})=><Card className="p-4" key={record.Registro_ID}><p className="font-extrabold"><ProgressMetrics record={record}/></p><p className="mt-1 text-sm text-slate-700">{catalog?.Ejercicio??"Ejercicio"}</p><p className="mt-3 text-xs text-slate-500">{new Date(record.Fecha_Registro).toLocaleDateString("es-AR")}</p></Card>)}</div>:<EmptyState icon="↗" title="Tu progreso empieza con una marca" description="Registrar peso, repeticiones o tiempo es opcional y podés hacerlo desde cada ejercicio."/>}<Link className="brand-link inline-flex min-h-11 items-center font-bold" href="/progreso">Ver todas tus marcas →</Link></section></main></>}
